// Y.Doc projection — file rollup only, post-AD-2.
//
// Under AD-2 the durable record for cells lives in the event log; the
// projection is written by the event handlers (events/event-projection.ts).
// The Y.Doc that y-partyserver maintains for live focus locks is no longer
// the source of truth for the `cells` table.
//
// What remains here is a small file-row rollup pass: counters that the
// dashboard wants without scanning every event. These numbers will be
// regenerated by the event-driven projection in Phase 2; until then the
// onSave path writes them so the file listing stays approximately current.

import * as Y from "yjs"

export interface FileRollup {
  fileId: string
  projectId: string
  name: string
  fileType: string
  sourceLanguage: string | null
  targetLanguage: string | null
  cellCount: number
  approvedCount: number
  wordCount: number
  lastEditAt: number | null
}

export interface ProjectionResult {
  file: FileRollup
}

export function projectDoc(
  projectId: string,
  fileId: string,
  doc: Y.Doc,
): ProjectionResult {
  const meta = doc.getMap("meta")
  const cellsMap = doc.getMap("cells")

  let cellCount = 0
  let approvedCount = 0
  let totalWords = 0
  let maxEditAt = 0

  for (const cellId of cellsMap.keys()) {
    const cellNode = cellsMap.get(cellId)
    if (!(cellNode instanceof Y.Map)) continue
    cellCount += 1

    const frag = cellNode.get("translatedXml")
    if (frag instanceof Y.XmlFragment) {
      totalWords += countWords(extractPlainText(frag))
    }

    const history = cellNode.get("history")
    if (history instanceof Y.Array) {
      const entries = history.toArray() as Array<{
        timestamp?: string
        validated?: boolean
      }>
      let cellValidated = false
      for (const entry of entries) {
        if (!entry) continue
        const ts = entry.timestamp ? Date.parse(entry.timestamp) : NaN
        if (Number.isFinite(ts) && ts > maxEditAt) maxEditAt = ts
        if (entry.validated === true) cellValidated = true
      }
      if (cellValidated) approvedCount += 1
    }
  }

  return {
    file: {
      fileId,
      projectId,
      name: (meta.get("fileName") as string | undefined) ?? "",
      fileType: (meta.get("fileType") as string | undefined) ?? "codex",
      sourceLanguage: (meta.get("sourceLanguage") as string | undefined) ?? null,
      targetLanguage: (meta.get("targetLanguage") as string | undefined) ?? null,
      cellCount,
      approvedCount,
      wordCount: totalWords,
      lastEditAt: maxEditAt > 0 ? maxEditAt : null,
    },
  }
}

function extractPlainText(frag: Y.XmlFragment): string {
  const parts: string[] = []
  for (let i = 0; i < frag.length; i++) {
    const node = frag.get(i)
    if (node instanceof Y.XmlText) {
      parts.push(node.toString())
    } else if (node instanceof Y.XmlElement) {
      parts.push(extractTextFromElement(node))
      parts.push(" ")
    }
  }
  return parts.join("").replace(/\s+/g, " ").trim()
}

function extractTextFromElement(el: Y.XmlElement): string {
  const parts: string[] = []
  for (let i = 0; i < el.length; i++) {
    const child = el.get(i)
    if (child instanceof Y.XmlText) {
      parts.push(child.toString())
    } else if (child instanceof Y.XmlElement) {
      parts.push(extractTextFromElement(child))
    }
  }
  return parts.join("")
}

function countWords(text: string): number {
  const trimmed = text.trim()
  if (!trimmed) return 0
  return trimmed.split(/\s+/).length
}

/**
 * Update only the file-level rollup row in D1. Cells are no longer written
 * from the Y.Doc — that's the event log's job under AD-2.
 */
export async function writeProjection(
  db: D1Database,
  result: ProjectionResult,
  projectedFrom: string,
): Promise<void> {
  const fileStmt = db.prepare(
    `INSERT INTO files (
      id, project_id, name, file_type, source_language, target_language,
      cell_count, approved_count, word_count, last_edit_at, projected_from,
      updated_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, unixepoch('now') * 1000)
    ON CONFLICT(id) DO UPDATE SET
      name = excluded.name,
      file_type = excluded.file_type,
      source_language = excluded.source_language,
      target_language = excluded.target_language,
      cell_count = excluded.cell_count,
      approved_count = excluded.approved_count,
      word_count = excluded.word_count,
      last_edit_at = excluded.last_edit_at,
      projected_from = excluded.projected_from,
      updated_at = unixepoch('now') * 1000`,
  )

  await db.batch([
    fileStmt.bind(
      result.file.fileId,
      result.file.projectId,
      result.file.name,
      result.file.fileType,
      result.file.sourceLanguage,
      result.file.targetLanguage,
      result.file.cellCount,
      result.file.approvedCount,
      result.file.wordCount,
      result.file.lastEditAt,
      projectedFrom,
    ),
  ])
}

// ── Legacy compatibility shims ──────────────────────────────────────────
//
// The Phase 0 fingerprint diff is no longer relevant now that cells aren't
// projected from the doc, but other modules import these names — keep
// stubs so the rest of the worker builds while Phase 2 reshapes the call
// sites.

export interface CellProjection {
  fileId: string
  cellId: string
  contentText: string
  contentHash: string
  validated: 0 | 1
  wordCount: number
  lastEditor: string | null
  lastEditAt: number
}

export function cellFingerprint(c: CellProjection): string {
  return `${c.contentHash}|${c.validated}|${c.wordCount}|${c.lastEditAt}|${c.lastEditor ?? ""}`
}

export function diffProjection(
  result: ProjectionResult,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  _prior: Map<string, string>,
): ProjectionResult {
  return result
}
