// Builds the copy-and-paste prompt a user hands to their agent along with a
// freshly minted `aqk_…` token (Preferences → Account → API tokens).
//
// WHY this prompt teaches discovery instead of teaching the API: the Agent API
// already describes itself. `GET /api/v1/external` is unauthenticated and
// returns the live endpoint map, the prepare→commit model, the error-code set,
// and the MCP setup — all generated by the running server
// (sync-worker/src/external/discovery-route.ts); `get_capabilities` is its MCP
// twin. Anything this prompt restated would be a second copy that drifts every
// time an endpoint or command kind is added, and a pasted prompt is the one
// place we can never go back and update. So the prompt carries only:
//
//   1. what genuinely cannot be discovered — the base URL, the token, the
//      header shape (you need all three before any request works);
//   2. an explicit instruction to fetch the map first and treat it, not this
//      message, as the source of truth;
//   3. the ask/act approval discipline — a standing policy the human is setting
//      for the agent, not an API fact that can go stale.
//
// Adding a "here are the endpoints / command kinds" section to this string
// would defeat the point. Let the API answer that question.

import type { CredentialMode } from "./credentials"

/** Placeholder used when the plaintext token isn't available (the show-once
 * dialog is the only moment it is). */
export const TOKEN_PLACEHOLDER = "aqk_paste_your_token_here"

export interface AgentInstructionsInput {
  /** HTTP origin of the sync worker, e.g. `https://api.aquilla.app/sync`. */
  syncOrigin: string
  /** Plaintext token, or omit for the placeholder. */
  token?: string
  mode: CredentialMode
  /** Human-readable scope, e.g. `project "Blackfoot NT"`. */
  scopeLabel: string
}

export function buildAgentInstructions({
  syncOrigin,
  token,
  mode,
  scopeLabel,
}: AgentInstructionsInput): string {
  const base = `${syncOrigin.replace(/\/+$/, "")}/api/v1/external`
  const tok = token ?? TOKEN_PLACEHOLDER

  const modeLine =
    mode === "ask"
      ? "ask — you can stage writes, but nothing is applied until I approve it in my browser."
      : "act — writes you commit are applied immediately. Be careful, and tell me what you changed."

  // Prose lines are deliberately unwrapped: the dialog and most agent chats
  // soft-wrap them, and hard newlines mid-sentence would wrap twice and read ragged.
  const modeRule =
    mode === "ask"
      ? `Because this token is ask-mode, a commit will come back asking for human approval, with a URL. That URL is for me, not you: paste it to me, stop, and wait. Don't retry the commit in a loop while you wait — retry it once, after I tell you I've approved. You cannot skip or automate this step, and you shouldn't try to.`
      : `Because this token is act-mode, a commit really does apply. Always stage first and read back the effect summary the server computes; only commit once it matches what I actually asked for. Tell me what you changed afterwards.`

  return `I've given you access to my Aquilla translation workspace through its Agent API.

API base: ${base}
Token:    ${tok}
Header:   Authorization: Bearer ${tok}
Mode:     ${modeLine}
Scope:    ${scopeLabel}

Don't take my word for what this API can do — ask it. Before anything else, fetch ${base} itself. It needs no auth and returns a machine-readable map of the live API: every endpoint, the read/write model, the full error-code list, and how to connect over MCP. The server generates that map from what it is actually running, so it is always current. This message isn't — it's a snapshot from whenever I pasted it. Where the two disagree, the API is right.

Then GET ${base}/me to confirm the token works and see the mode and scope above from the server's side, and GET ${base}/projects to see what it can reach. From there, follow the map. Explore rather than guess: any path that doesn't exist returns a JSON 404 pointing you back to the map, so a wrong turn is cheap and self-correcting, and every error carries a stable code telling you whether to fix, re-prepare, back off, or stop and ask me.

One standing rule that isn't the API's to change — it's mine. ${modeRule}

Prefer MCP over REST? Same token, same permissions, and get_capabilities is the discovery call to make first:
  claude mcp add aquilla --transport http "${base}/mcp" --header "Authorization: Bearer ${tok}"

What I'd like you to do: <describe your task here>
`
}
