/**
 * Tests for src/lib/completion/interlinear.ts
 *
 * Uses a small parallel corpus of English/French Bible-style verse pairs as
 * the ground truth. The corpus is large enough to exercise both the cold-start
 * (Dice) and warm (EM) paths.
 */

import { describe, it, expect } from "vitest"
import {
  buildAlignmentModel,
  alignCell,
  confirmAlignment,
  invalidateAlignment,
  CONFIDENCE_MIN,
  CONFIDENCE_AMBER,
  CONFIDENCE_HIGH,
  type AlignmentSeed,
} from "./interlinear"

// ── Shared corpus ─────────────────────────────────────────────────────────────

/** 10 English/French verse pairs — exercises cold-start Dice path. */
const SMALL_CORPUS = [
  { source: "In the beginning God created the heavens and the earth",
    target: "Au commencement Dieu créa les cieux et la terre" },
  { source: "God saw that the light was good",
    target: "Dieu vit que la lumière était bonne" },
  { source: "God said let there be light and there was light",
    target: "Dieu dit que la lumière soit et la lumière fut" },
  { source: "The earth was without form and void",
    target: "La terre était informe et vide" },
  { source: "God blessed the seventh day",
    target: "Dieu bénit le septième jour" },
  { source: "God called the dry land earth",
    target: "Dieu appela la terre sèche" },
  { source: "God created man in his own image",
    target: "Dieu créa l homme à son image" },
  { source: "God saw everything that he had made",
    target: "Dieu vit tout ce qu il avait fait" },
  { source: "God rested on the seventh day",
    target: "Dieu se reposa le septième jour" },
  { source: "God spoke all these words",
    target: "Dieu prononça toutes ces paroles" },
]

/**
 * 50 pairs — forces the warm EM path (>= WARM_THRESHOLD = 50).
 * Generated by repeating the small corpus with slight variation so the
 * vocabulary is stable but EM has enough data to converge.
 */
const WARM_CORPUS = (() => {
  const extras = [
    { source: "the spirit of God moved over the waters",
      target: "l esprit de Dieu se mouvait sur les eaux" },
    { source: "God divided the light from the darkness",
      target: "Dieu sépara la lumière des ténèbres" },
    { source: "God called the light day",
      target: "Dieu appela la lumière jour" },
    { source: "God called the darkness night",
      target: "Dieu appela les ténèbres nuit" },
    { source: "God made the two great lights",
      target: "Dieu fit les deux grandes lumières" },
    { source: "God set them in the firmament",
      target: "Dieu les plaça dans le firmament" },
    { source: "God saw that it was good",
      target: "Dieu vit que c était bon" },
    { source: "God made the beasts of the earth",
      target: "Dieu fit les bêtes de la terre" },
    { source: "God made man from the dust of the earth",
      target: "Dieu forma l homme de la poussière de la terre" },
    { source: "God breathed into his nostrils",
      target: "Dieu insuffla dans ses narines" },
    { source: "God planted a garden in Eden",
      target: "Dieu planta un jardin en Éden" },
    { source: "God took the man and put him in the garden",
      target: "Dieu prit l homme et le plaça dans le jardin" },
    { source: "God commanded the man saying",
      target: "Dieu commanda à l homme en disant" },
    { source: "God brought the animals to Adam",
      target: "Dieu amena les animaux vers Adam" },
    { source: "God caused a deep sleep to fall",
      target: "Dieu fit tomber un profond sommeil" },
    { source: "God made a woman from the rib",
      target: "Dieu forma une femme de la côte" },
    { source: "God said to the serpent",
      target: "Dieu dit au serpent" },
    { source: "God said to the woman",
      target: "Dieu dit à la femme" },
    { source: "God made garments of skin for them",
      target: "Dieu fit des vêtements de peau pour eux" },
    { source: "God sent him out of the garden",
      target: "Dieu le chassa du jardin" },
    { source: "God placed cherubim at the east",
      target: "Dieu plaça des chérubins à l est" },
    { source: "God had regard for Abel",
      target: "Dieu eut égard à Abel" },
    { source: "God spoke to Noah saying",
      target: "Dieu parla à Noé en disant" },
    { source: "God established his covenant",
      target: "Dieu établit son alliance" },
    { source: "God blessed Noah and his sons",
      target: "Dieu bénit Noé et ses fils" },
    { source: "God remembered Noah",
      target: "Dieu se souvint de Noé" },
    { source: "God made a wind blow over the earth",
      target: "Dieu fit souffler un vent sur la terre" },
    { source: "God said in his heart",
      target: "Dieu dit en son cœur" },
    { source: "God called Abram",
      target: "Dieu appela Abram" },
    { source: "God said to Abram go from your country",
      target: "Dieu dit à Abram va de ton pays" },
    { source: "God appeared to Abram",
      target: "Dieu apparut à Abram" },
    { source: "God said I am your shield",
      target: "Dieu dit je suis ton bouclier" },
    { source: "God made a covenant with Abram",
      target: "Dieu conclut une alliance avec Abram" },
    { source: "God heard the voice of the boy",
      target: "Dieu entendit la voix du garçon" },
    { source: "God opened her eyes",
      target: "Dieu lui ouvrit les yeux" },
    { source: "God was with the boy",
      target: "Dieu était avec le garçon" },
    { source: "God tested Abraham",
      target: "Dieu mit Abraham à l épreuve" },
    { source: "God said take your son",
      target: "Dieu dit prends ton fils" },
    { source: "God called to Abraham a second time",
      target: "Dieu appela Abraham une seconde fois" },
    { source: "God will provide himself a lamb",
      target: "Dieu se pourvoira lui même un agneau" },
  ]
  return [...SMALL_CORPUS, ...extras]
})()

// ── Sanity checks on constants ─────────────────────────────────────────────────

describe("confidence threshold constants", () => {
  it("exports CONFIDENCE_MIN < CONFIDENCE_AMBER < CONFIDENCE_HIGH", () => {
    expect(CONFIDENCE_MIN).toBeLessThan(CONFIDENCE_AMBER)
    expect(CONFIDENCE_AMBER).toBeLessThan(CONFIDENCE_HIGH)
  })

  it("thresholds are in [0, 1]", () => {
    expect(CONFIDENCE_MIN).toBeGreaterThanOrEqual(0)
    expect(CONFIDENCE_HIGH).toBeLessThanOrEqual(1)
  })
})

// ── Cold-start (Dice) path ───────────────────────────────────────────────────

describe("buildAlignmentModel — cold-start Dice path", () => {
  it("returns a cold model for < 50 pairs", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    expect(model.isWarm).toBe(false)
    expect(model.pairCount).toBe(SMALL_CORPUS.length)
  })

  it("alignCell returns links on a known pair in the corpus", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    const links = alignCell(
      "God created the heavens",
      "Dieu créa les cieux",
      model,
    )
    expect(links.length).toBeGreaterThan(0)
    // "god" ↔ "dieu" should appear as a high-confidence link
    const godLink = links.find((l) => l.srcToken === "god" && l.tgtToken === "dieu")
    expect(godLink).toBeDefined()
    expect(godLink!.confidence).toBeGreaterThan(CONFIDENCE_MIN)
  })

  it("alignCell links have confidence in [0, 1]", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    const links = alignCell(
      "God said let there be light",
      "Dieu dit que la lumière soit",
      model,
    )
    for (const l of links) {
      expect(l.confidence).toBeGreaterThanOrEqual(0)
      expect(l.confidence).toBeLessThanOrEqual(1)
    }
  })

  it("alignCell threshold filter works", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    const allLinks = alignCell(
      "God created the heavens",
      "Dieu créa les cieux",
      model,
      { threshold: 0 },
    )
    const highLinks = alignCell(
      "God created the heavens",
      "Dieu créa les cieux",
      model,
      { threshold: CONFIDENCE_HIGH },
    )
    // High threshold should return fewer (or equal) links
    expect(highLinks.length).toBeLessThanOrEqual(allLinks.length)
    for (const l of highLinks) {
      expect(l.confidence).toBeGreaterThanOrEqual(CONFIDENCE_HIGH)
    }
  })

  it("returns empty array for empty source", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    expect(alignCell("", "Dieu créa", model)).toEqual([])
  })

  it("returns empty array for empty target", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    expect(alignCell("God created", "", model)).toEqual([])
  })

  it("returns empty array for completely unseen tokens (threshold 0.1)", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    // Neither side was in training corpus
    const links = alignCell("xyzzy plugh", "zork frotz", model)
    expect(links).toEqual([])
  })

  it("excludes low-confidence noise below default threshold", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    const links = alignCell(
      "God created",
      "Dieu créa",
      model,
    )
    for (const l of links) {
      expect(l.confidence).toBeGreaterThanOrEqual(CONFIDENCE_MIN)
    }
  })
})

// ── Warm (EM) path ────────────────────────────────────────────────────────────

describe("buildAlignmentModel — warm EM path", () => {
  it("returns a warm model for >= 50 pairs", () => {
    const model = buildAlignmentModel(WARM_CORPUS)
    expect(model.isWarm).toBe(true)
    expect(model.pairCount).toBe(WARM_CORPUS.length)
  })

  it("EM model aligns 'god' ↔ 'dieu' with high confidence", () => {
    const model = buildAlignmentModel(WARM_CORPUS)
    const links = alignCell(
      "God created the heavens and the earth",
      "Dieu créa les cieux et la terre",
      model,
    )
    const godLink = links.find((l) => l.srcToken === "god" && l.tgtToken === "dieu")
    expect(godLink).toBeDefined()
    // EM with 50 pairs should push god↔dieu well above amber
    expect(godLink!.confidence).toBeGreaterThan(CONFIDENCE_AMBER)
  })

  it("EM model links have confidence in [0, 1]", () => {
    const model = buildAlignmentModel(WARM_CORPUS)
    const links = alignCell(
      "God said let there be light",
      "Dieu dit que la lumière soit",
      model,
      { threshold: 0 },
    )
    for (const l of links) {
      expect(l.confidence).toBeGreaterThanOrEqual(0)
      expect(l.confidence).toBeLessThanOrEqual(1)
    }
  })

  it("EM model is deterministic: same inputs → same output", () => {
    const model1 = buildAlignmentModel(WARM_CORPUS)
    const model2 = buildAlignmentModel(WARM_CORPUS)
    const links1 = alignCell("God created", "Dieu créa", model1)
    const links2 = alignCell("God created", "Dieu créa", model2)
    expect(links1).toEqual(links2)
  })

  it("cold model is also deterministic", () => {
    const model1 = buildAlignmentModel(SMALL_CORPUS)
    const model2 = buildAlignmentModel(SMALL_CORPUS)
    const links1 = alignCell("God said", "Dieu dit", model1)
    const links2 = alignCell("God said", "Dieu dit", model2)
    expect(links1).toEqual(links2)
  })
})

// ── Online update hooks ───────────────────────────────────────────────────────

describe("confirmAlignment", () => {
  it("increases confidence of confirmed pair", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    const before = alignCell("God created", "Dieu créa", model, { threshold: 0 })
    const godBefore = before.find((l) => l.srcToken === "god" && l.tgtToken === "dieu")
    const confidenceBefore = godBefore?.confidence ?? 0

    confirmAlignment("god", "dieu", model)

    const after = alignCell("God created", "Dieu créa", model, { threshold: 0 })
    const godAfter = after.find((l) => l.srcToken === "god" && l.tgtToken === "dieu")
    const confidenceAfter = godAfter?.confidence ?? 0

    expect(confidenceAfter).toBeGreaterThanOrEqual(confidenceBefore)
  })

  it("is idempotent in that calling it multiple times only increases confidence", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    confirmAlignment("god", "dieu", model)
    const links1 = alignCell("God created", "Dieu créa", model, { threshold: 0 })
    const c1 = links1.find((l) => l.srcToken === "god" && l.tgtToken === "dieu")?.confidence ?? 0

    confirmAlignment("god", "dieu", model)
    const links2 = alignCell("God created", "Dieu créa", model, { threshold: 0 })
    const c2 = links2.find((l) => l.srcToken === "god" && l.tgtToken === "dieu")?.confidence ?? 0

    expect(c2).toBeGreaterThanOrEqual(c1)
  })
})

describe("invalidateAlignment", () => {
  it("decreases or zeroes confidence of invalidated pair", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    const before = alignCell("God created", "Dieu créa", model, { threshold: 0 })
    const godBefore = before.find((l) => l.srcToken === "god" && l.tgtToken === "dieu")
    const confidenceBefore = godBefore?.confidence ?? 0

    // Invalidate many times to push it down
    invalidateAlignment("god", "dieu", model)
    invalidateAlignment("god", "dieu", model)
    invalidateAlignment("god", "dieu", model)

    const after = alignCell("God created", "Dieu créa", model, { threshold: 0 })
    const godAfter = after.find((l) => l.srcToken === "god" && l.tgtToken === "dieu")
    const confidenceAfter = godAfter?.confidence ?? 0

    expect(confidenceAfter).toBeLessThanOrEqual(confidenceBefore)
  })

  it("does not produce negative counts (no crash)", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    // Invalidate far more times than any count could be — should not throw
    for (let i = 0; i < 20; i++) {
      invalidateAlignment("god", "dieu", model)
    }
    expect(() =>
      alignCell("God created", "Dieu créa", model, { threshold: 0 }),
    ).not.toThrow()
  })
})

// ── Seeds ────────────────────────────────────────────────────────────────────

describe("AlignmentSeed integration", () => {
  it("positive seed boosts alignment of seeded pair", () => {
    const modelWithout = buildAlignmentModel(SMALL_CORPUS)
    const seeds: AlignmentSeed[] = [{ srcToken: "earth", tgtToken: "terre", weight: 10 }]
    const modelWith = buildAlignmentModel(SMALL_CORPUS, seeds)

    const linksWithout = alignCell(
      "the earth was good",
      "la terre était bonne",
      modelWithout,
      { threshold: 0 },
    )
    const linksWith = alignCell(
      "the earth was good",
      "la terre était bonne",
      modelWith,
      { threshold: 0 },
    )

    const cWithout = linksWithout.find(
      (l) => l.srcToken === "earth" && l.tgtToken === "terre",
    )?.confidence ?? 0
    const cWith = linksWith.find(
      (l) => l.srcToken === "earth" && l.tgtToken === "terre",
    )?.confidence ?? 0

    expect(cWith).toBeGreaterThanOrEqual(cWithout)
  })

  it("negative seed penalizes alignment", () => {
    const modelWithout = buildAlignmentModel(SMALL_CORPUS)
    const seeds: AlignmentSeed[] = [{ srcToken: "god", tgtToken: "dieu", weight: -5 }]
    const modelWith = buildAlignmentModel(SMALL_CORPUS, seeds)

    const linksWithout = alignCell("God said", "Dieu dit", modelWithout, { threshold: 0 })
    const linksWithSeeds = alignCell("God said", "Dieu dit", modelWith, { threshold: 0 })

    const cWithout = linksWithout.find((l) => l.srcToken === "god" && l.tgtToken === "dieu")?.confidence ?? 0
    const cWith = linksWithSeeds.find((l) => l.srcToken === "god" && l.tgtToken === "dieu")?.confidence ?? 0
    expect(cWith).toBeLessThanOrEqual(cWithout)
  })
})

// ── Link structure ────────────────────────────────────────────────────────────

describe("AlignmentLink structure", () => {
  it("links have all required fields", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    const links = alignCell("God created", "Dieu créa", model)
    for (const l of links) {
      expect(typeof l.srcIndex).toBe("number")
      expect(typeof l.srcToken).toBe("string")
      expect(typeof l.tgtIndex).toBe("number")
      expect(typeof l.tgtToken).toBe("string")
      expect(typeof l.confidence).toBe("number")
    }
  })

  it("links are sorted by srcIndex", () => {
    const model = buildAlignmentModel(SMALL_CORPUS)
    const links = alignCell(
      "In the beginning God created the heavens",
      "Au commencement Dieu créa les cieux",
      model,
    )
    for (let i = 1; i < links.length; i++) {
      expect(links[i].srcIndex).toBeGreaterThanOrEqual(links[i - 1].srcIndex)
    }
  })

  it("srcIndex and tgtIndex are within token array bounds", () => {
    const source = "God said let there be light"
    const target = "Dieu dit que la lumière soit"
    const srcLen = source.split(/\s+/).filter(Boolean).length
    const tgtLen = target.split(/\s+/).filter(Boolean).length

    const model = buildAlignmentModel(SMALL_CORPUS)
    const links = alignCell(source, target, model)
    for (const l of links) {
      expect(l.srcIndex).toBeGreaterThanOrEqual(0)
      expect(l.srcIndex).toBeLessThan(srcLen)
      expect(l.tgtIndex).toBeGreaterThanOrEqual(0)
      expect(l.tgtIndex).toBeLessThan(tgtLen)
    }
  })
})

// ── Empty / edge cases ────────────────────────────────────────────────────────

describe("edge cases", () => {
  it("buildAlignmentModel with empty pairs is safe", () => {
    const model = buildAlignmentModel([])
    expect(model.pairCount).toBe(0)
    expect(model.isWarm).toBe(false)
    expect(alignCell("hello", "bonjour", model)).toEqual([])
  })

  it("buildAlignmentModel with single pair is safe", () => {
    const model = buildAlignmentModel([{ source: "God", target: "Dieu" }])
    const links = alignCell("God", "Dieu", model, { threshold: 0 })
    expect(links.length).toBeGreaterThan(0)
  })

  it("seeds on an empty corpus produce links", () => {
    const seeds: AlignmentSeed[] = [
      { srcToken: "God", tgtToken: "Dieu", weight: 10 },
    ]
    const model = buildAlignmentModel([], seeds)
    const links = alignCell("God", "Dieu", model, { threshold: 0 })
    expect(links.length).toBeGreaterThan(0)
    expect(links[0].srcToken).toBe("god")
    expect(links[0].tgtToken).toBe("dieu")
  })
})
