# Template for per-PR sync-worker variants. Generated by
# .github/workflows/pr-db-fork.yml at PR-open / sync time. Placeholders
# (__PR__, __DB_ID__) are sed-substituted before wrangler reads it.
#
# Behavior:
# - Each PR with migration changes gets its own forked D1 (aquilla-pr-N)
#   so the migration can be applied without polluting the shared staging
#   DB.
# - R2 is shared with staging (aquilla-snapshots-staging) but namespaced
#   via R2_KEY_PREFIX=pr-N so snapshots from different PRs don't collide.
# - Durable Object namespace is implicitly per-worker (different worker
#   name → different namespace).
# - Runs in ALLOW_UNAUTHENTICATED mode — the PR-specific worker URL is
#   semi-hidden behind the PR-only build (preview Pages bundle) and the
#   data is staging-only. Real-auth seeding per PR would require feeding
#   SYNC_SECRET_KEY via GH Actions secrets; deferred until needed.
#
# DO NOT edit the placeholders by hand. The workflow substitutes them.

name = "aquilla-sync-worker-pr-__PR__"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
account_id = "6a80496d1e59948a9cbaa3c643ba81d7"

[[durable_objects.bindings]]
name = "FileSync"
class_name = "FileSync"

[[durable_objects.bindings]]
name = "ProjectSync"
class_name = "ProjectSync"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FileSync"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ProjectSync"]

[[r2_buckets]]
binding = "SNAPSHOTS"
bucket_name = "aquilla-snapshots-staging"

[[d1_databases]]
binding = "AQUILLA_DB"
database_name = "aquilla-pr-__PR__"
database_id = "__DB_ID__"

[vars]
R2_KEY_PREFIX = "pr-__PR__"
ALLOW_UNAUTHENTICATED = "true"
