// Compile the CC0 OpenBible section-counts dataset into the app's lookup table.
//
//   pnpm tsx scripts/build-section-boundaries.ts            # fetch upstream
//   pnpm tsx scripts/build-section-boundaries.ts <file.txt> # from a local copy
//
// Writes src/lib/import/data/section-boundaries.ts. Re-run it to refresh the
// data; the committed output is the artifact the app reads (see
// src/lib/import/section-boundaries.ts for why the compile happens here rather
// than at runtime).
//
// AQU-1387.

import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const SOURCE_URL = "https://a.openbible.info/data/bible-section-counts.txt"
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const OUTPUT = resolve(SCRIPT_DIR, "../src/lib/import/data/section-boundaries.ts")

/**
 * Upstream book abbreviations → USFM codes. Upstream ships the 66-book
 * Protestant canon; anything outside this map is dropped with a warning rather
 * than guessed at, because a wrong book code would silently attach one book's
 * pericopes to another.
 */
const USFM_BY_UPSTREAM: Record<string, string> = {
  Gen: "GEN", Exod: "EXO", Lev: "LEV", Num: "NUM", Deut: "DEU",
  Josh: "JOS", Judg: "JDG", Ruth: "RUT", "1Sam": "1SA", "2Sam": "2SA",
  "1Kgs": "1KI", "2Kgs": "2KI", "1Chr": "1CH", "2Chr": "2CH",
  Ezra: "EZR", Neh: "NEH", Esth: "EST", Job: "JOB", Ps: "PSA",
  Prov: "PRO", Eccl: "ECC", Song: "SNG", Isa: "ISA", Jer: "JER",
  Lam: "LAM", Ezek: "EZK", Dan: "DAN", Hos: "HOS", Joel: "JOL",
  Amos: "AMO", Obad: "OBA", Jonah: "JON", Mic: "MIC", Nah: "NAM",
  Hab: "HAB", Zeph: "ZEP", Hag: "HAG", Zech: "ZEC", Mal: "MAL",
  Matt: "MAT", Mark: "MRK", Luke: "LUK", John: "JHN", Acts: "ACT",
  Rom: "ROM", "1Cor": "1CO", "2Cor": "2CO", Gal: "GAL", Eph: "EPH",
  Phil: "PHP", Col: "COL", "1Thess": "1TH", "2Thess": "2TH",
  "1Tim": "1TI", "2Tim": "2TI", Titus: "TIT", Phlm: "PHM",
  Heb: "HEB", Jas: "JAS", "1Pet": "1PE", "2Pet": "2PE",
  "1John": "1JN", "2John": "2JN", "3John": "3JN", Jude: "JUD", Rev: "REV",
}

async function readSource(argument: string | undefined): Promise<string> {
  if (argument) return readFile(resolve(argument), "utf8")
  const response = await fetch(SOURCE_URL)
  if (!response.ok) {
    throw new Error(`${SOURCE_URL} responded ${response.status}`)
  }
  return response.text()
}

function main(source: string): { body: string; chapters: number; verses: number } {
  // chapterKey → verse → translations that START a section at that verse.
  const starts = new Map<string, Map<number, number>>()
  const unknownBooks = new Set<string>()
  let rows = 0

  for (const rawLine of source.split("\n")) {
    const line = rawLine.trim()
    if (!line || line.startsWith("#")) continue
    const columns = line.split("\t")
    if (columns.length < 4) continue
    const start = columns[0].split(".")
    const translations = Number(columns[3])
    if (start.length !== 3 || !Number.isFinite(translations)) continue
    const book = USFM_BY_UPSTREAM[start[0]]
    if (!book) {
      unknownBooks.add(start[0])
      continue
    }
    const chapter = Number(start[1])
    const verse = Number(start[2])
    if (!Number.isInteger(chapter) || !Number.isInteger(verse)) continue
    const key = `${book}.${chapter}`
    const chapterStarts = starts.get(key) ?? new Map<number, number>()
    // Every row sharing a start verse is a different section THE SAME verse
    // opens, chosen by a disjoint set of translations — so the counts add.
    chapterStarts.set(verse, (chapterStarts.get(verse) ?? 0) + translations)
    starts.set(key, chapterStarts)
    rows += 1
  }

  if (unknownBooks.size > 0) {
    console.warn(`skipped unmapped books: ${[...unknownBooks].sort().join(", ")}`)
  }

  let verses = 0
  const lines = [...starts.entries()]
    .sort(([left], [right]) => compareChapterKeys(left, right))
    .map(([key, chapterStarts]) => {
      const pairs = [...chapterStarts.entries()]
        .sort(([left], [right]) => left - right)
        .map(([verse, translations]) => `${verse}:${translations}`)
      verses += pairs.length
      return `${key} ${pairs.join(" ")}`
    })

  console.log(`${rows} upstream rows → ${starts.size} chapters, ${verses} section starts`)
  return { body: lines.join("\n"), chapters: starts.size, verses }
}

function compareChapterKeys(left: string, right: string): number {
  const [leftBook, leftChapter] = left.split(".")
  const [rightBook, rightChapter] = right.split(".")
  if (leftBook !== rightBook) return leftBook < rightBook ? -1 : 1
  return Number(leftChapter) - Number(rightChapter)
}

const [, , sourceArgument] = process.argv
const source = await readSource(sourceArgument)
const { body, chapters, verses } = main(source)

const module = `// GENERATED by scripts/build-section-boundaries.ts — do not edit by hand.
//
// Source: ${SOURCE_URL}
// License: CC0 1.0 (public domain dedication) — OpenBible.info
// Compiled: ${new Date().toISOString().slice(0, 10)}
// Shape: one line per chapter, \`BOOK.CHAPTER verse:translations …\`, where
//   \`translations\` is how many of 20 published translations begin a section at
//   that verse. ${chapters} chapters, ${verses} section starts.
//
// Refresh with: pnpm tsx scripts/build-section-boundaries.ts

export const SECTION_BOUNDARIES_CC0 = \`${body}\`
`

await mkdir(dirname(OUTPUT), { recursive: true })
await writeFile(OUTPUT, module, "utf8")
console.log(`wrote ${OUTPUT}`)
