/**
 * AQU-1456 — regenerate `src/lib/languages/iso-639-3-table.ts` from SIL's
 * authoritative ISO 639-3 code table.
 *
 *   pnpm tsx scripts/build-iso-639-3-table.ts
 *
 * Source of truth is SIL's published `iso-639-3.tab` (the same file Codex's
 * `src/utils/languageUtils.ts` was generated from). We re-derive from the tab
 * rather than copying Codex's array because Codex's `Ref_Name` values are
 * space-stripped ("EasternArrernte"); the tab carries the real display names.
 *
 * Only three columns survive into the app: the 639-3 id, the 639-1 two-letter
 * code where SIL lists one, and the reference name. The generated module is a
 * single tab-separated string constant so `tsc` sees one literal instead of
 * ~7,900 object literals, and so the chunk gzips well.
 */

import { writeFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import path from "node:path"

const SOURCE_URL =
  "https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab"

/**
 * Not part of ISO 639-3. Codex pins it at the top of its own picker so Bible
 * translators can name their source lane in one pick; `blg` is unassigned in
 * the standard, so there is no collision.
 */
const BIBLICAL_LANGUAGES = { id: "blg", part1: "", name: "Biblical Hebrew/Aramaic/Greek" }

type Row = { id: string; part1: string; name: string }

function parse(tab: string): Row[] {
  const lines = tab.split(/\r?\n/)
  const header = lines[0]?.split("\t") ?? []
  const col = (label: string) => {
    const index = header.indexOf(label)
    if (index < 0) throw new Error(`iso-639-3.tab is missing the ${label} column`)
    return index
  }
  const idAt = col("Id")
  const part1At = col("Part1")
  const nameAt = col("Ref_Name")

  const rows: Row[] = []
  for (const line of lines.slice(1)) {
    if (!line.trim()) continue
    const cells = line.split("\t")
    const id = cells[idAt]?.trim() ?? ""
    const name = cells[nameAt]?.trim() ?? ""
    if (!/^[a-z]{3}$/.test(id) || !name) continue
    if (name.includes("\t") || name.includes("\n")) {
      throw new Error(`Ref_Name for ${id} contains a delimiter: ${name}`)
    }
    rows.push({ id, part1: cells[part1At]?.trim() ?? "", name })
  }
  if (rows.length < 7000) {
    throw new Error(`only ${rows.length} rows parsed — refusing to shrink the catalog`)
  }
  return rows
}

async function main(): Promise<void> {
  const response = await fetch(SOURCE_URL)
  if (!response.ok) {
    throw new Error(`GET ${SOURCE_URL} → ${response.status}`)
  }
  const rows = parse(await response.text())
  rows.sort((a, b) => a.name.localeCompare(b.name, "en"))

  const serialized = [BIBLICAL_LANGUAGES, ...rows]
    .map((row) => `${row.id}\t${row.part1}\t${row.name}`)
    .join("\n")

  const out = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    "..",
    "src/lib/languages/iso-639-3-table.ts",
  )
  await writeFile(
    out,
    `// GENERATED by scripts/build-iso-639-3-table.ts — do not edit by hand.
//
// AQU-1456 — the full SIL ISO 639-3 code table (${rows.length} languages:
// living, extinct, ancient, historical, constructed, sign and macro), plus the
// pinned non-standard "${BIBLICAL_LANGUAGES.id}" entry Codex offers for Bible source lanes.
//
// Source: ${SOURCE_URL}
//
// One line per language, tab-separated: 639-3 id, 639-1 code (empty when SIL
// lists none), reference name. Parsed by \`./full-catalog\`, which is the only
// module that should import this one — it is loaded through a dynamic import so
// the table lands in its own chunk rather than the initial bundle.
export const ISO_639_3_TABLE = ${JSON.stringify(serialized)}
`,
    "utf8",
  )
  console.log(`wrote ${out} (${rows.length} ISO 639-3 rows + 1 pinned)`)
}

await main()
