/**
 * Generates shared/tools/sdk/sdk-icons.ts: the lucide glyphs the extension
 * SDK draws (the SAME icons the built-in
 * editor uses, from the installed lucide-react), as inline SVG strings — the
 * sandboxed frame cannot load the app's icon components or fetch anything.
 *
 *   npx tsx scripts/gen-sdk-icons.ts
 */
import { readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { pathToFileURL } from "node:url"

export const EDITOR_ICONS = [
  "square-check", "flag", "hash", "type", "audio-lines", "chevron-down", "chevron-left", "chevron-right", "chevron-up",
  "languages", "plus", "check", "check-check", "circle", "message-circle", "triangle-alert", "git-branch-plus", "bold",
  "italic", "underline", "strikethrough", "code", "sparkles", "refresh-cw", "pilcrow-right", "pilcrow", "ellipsis", "mic",
  "upload", "play", "pause", "volume-2", "notebook-pen", "paperclip", "history", "activity", "file-text", "pencil",
  "trash-2", "x", "eye-off", "book-open", "corner-down-left", "search", "loader-circle", "lock", "arrow-right", "info",
  "git-branch", "user-round",
  // UI kit (aq.ui) extras for extensions
  "list", "layout-grid", "chart-column", "settings", "star", "funnel", "eye", "copy", "circle-check", "circle-alert", "clock", "users",
  "book", "bookmark", "save", "arrow-left", "arrow-up", "arrow-down", "external-link", "minus", "grip-vertical", "sliders-horizontal",
  "wand-sparkles", "target", "circle-dot", "hourglass", "gauge",
] as const

type Node = [string, Record<string, string>]

async function iconSvg(name: string): Promise<string> {
  const file = path.resolve("node_modules/lucide-react/dist/esm/icons", `${name}.mjs`)
  const mod = (await import(pathToFileURL(file).href)) as { __iconData?: { node: Node[] } }
  if (!mod.__iconData) {
    // An alias module (history → rotate-ccw-clock): follow the re-export.
    const alias = /from '\.\/([a-z0-9-]+)\.mjs'/.exec(await readFile(file, "utf8"))
    if (alias) return iconSvg(alias[1])
  }
  const nodes = mod.__iconData?.node
  if (!nodes) throw new Error(`no icon data for ${name}`)
  const inner = nodes
    .map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).filter(([k]) => k !== "key").map(([k, v]) => `${k}="${v}"`).join(" ")}/>`)
    .join("")
  return inner
}

async function main(): Promise<void> {
  const version = JSON.parse(await readFile("node_modules/lucide-react/package.json", "utf8")).version as string
  const entries: string[] = []
  for (const name of EDITOR_ICONS) entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(await iconSvg(name))},`)
  const out = `/**
 * GENERATED by scripts/gen-sdk-icons.ts from lucide-react ${version}
 * (ISC license) — do not edit. The lucide glyphs the extension SDK
 * (aq.icon) draws, as SVG inner markup.
 */
export const SDK_ICONS: Readonly<Record<string, string>> = {
${entries.join("\n")}
}
`
  await writeFile("shared/tools/sdk/sdk-icons.ts", out)
  console.log(`wrote ${EDITOR_ICONS.length} icons`)
}

void main()
