-- Aquilla Postgres schema — ported from Cloudflare D1 (SQLite).
-- Target: Neon Postgres 18, reached from Workers via Hyperdrive.
--
-- Translation rules (see docs/design/storage-migration-d1-to-neon.md):
--   • INTEGER PRIMARY KEY AUTOINCREMENT  -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--       (BY DEFAULT so the data migration can insert existing ids; reset the
--        identity sequence afterwards — see the bottom of this file.)
--   • STRICT / WITHOUT ROWID             -> removed (Postgres has neither)
--   • DATETIME DEFAULT CURRENT_TIMESTAMP -> TIMESTAMPTZ DEFAULT now()
--   • epoch-millisecond INTEGER columns  -> BIGINT
--   • REAL                               -> DOUBLE PRECISION
--   • 0/1 flag columns                   -> kept as INTEGER (app reads 0/1 — no app change)
--   • JSON-in-text (payload/settings/meta/preferences/…) -> kept as TEXT (app does JSON.parse)
--   • SQLite FTS5 (cells_fts + 3 sync triggers) -> a generated `value_tsv` tsvector
--       column on `cells` + a GIN index. 'simple' config (no stemming) because the
--       corpus is multilingual Bible text.
--   • FOREIGN KEY constraints are INTENTIONALLY OMITTED. SQLite ships with FK
--       enforcement OFF by default, so D1 never enforced these and the live data may
--       violate them; recreating them here would fail the bulk data load. PRIMARY KEY,
--       UNIQUE and CHECK (which SQLite DID enforce) are preserved. Add FKs later, once
--       the migrated data is verified clean, as DEFERRABLE constraints.
--
-- Excluded D1-internal/derived tables: _cf_KV, d1_migrations, cells_fts*.

-- ─────────────────────────────── identity ───────────────────────────────

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT UNIQUE NOT NULL,
    email         TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    preferences   TEXT NOT NULL DEFAULT '{}',
    created_at    TIMESTAMPTZ DEFAULT now(),
    updated_at    TIMESTAMPTZ DEFAULT now(),
    display_name  TEXT,
    avatar_url    TEXT,
    email_verified_at TIMESTAMPTZ
);

CREATE TABLE organizations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT,
    owner_user_id BIGINT NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT now(),
    updated_at    TIMESTAMPTZ DEFAULT now(),
    legacy_uuid   TEXT
);

CREATE TABLE org_members (
    org_id         BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    role_level     INTEGER NOT NULL,
    granted_by     BIGINT,
    granted_at     TIMESTAMPTZ DEFAULT now(),
    last_active_at TIMESTAMPTZ,
    PRIMARY KEY (org_id, user_id)
);

CREATE TABLE groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT NOT NULL,
    name        TEXT NOT NULL,
    description TEXT,
    created_by  BIGINT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ DEFAULT now(),
    legacy_uuid TEXT,
    is_internal BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (org_id, name)
);

CREATE TABLE group_members (
    group_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    added_by BIGINT,
    added_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (group_id, user_id)
);

CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token      TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Soft email verification (see migrations/0044_email_verification.sql).
CREATE TABLE email_verification_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token      TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_email_verification_tokens_token ON email_verification_tokens(token);

CREATE TABLE activity_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    activity_type     TEXT,
    description       TEXT,
    activity_metadata TEXT,
    timestamp         TIMESTAMPTZ DEFAULT now()
);

-- ─────────────────────────────── projects ───────────────────────────────

CREATE TABLE projects (
    id                TEXT PRIMARY KEY,
    name              TEXT NOT NULL,
    org_id            BIGINT,
    created_by        BIGINT NOT NULL,
    created_at        TIMESTAMPTZ DEFAULT now(),
    updated_at        TIMESTAMPTZ DEFAULT now(),
    archived_at       TIMESTAMPTZ,
    archived_by       BIGINT,
    source_project_id TEXT,
    deadline_at       TEXT,         -- calendar date string 'YYYY-MM-DD' (not an instant; TIMESTAMPTZ would TZ-shift it)
    -- Org termbase publish flag (migration 0030). TRUE = this project's termbase
    -- is discoverable by other projects in its org.
    org_published_termbase BOOLEAN NOT NULL DEFAULT FALSE,
    -- Active/inactive lifecycle flag (migration 0033). FALSE = frozen/dormant;
    -- deliberate reactivation required to edit. DISTINCT from archived_at
    -- (Trash): inactive projects remain visible in the list but block edits.
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    -- AQU-476: link metadata (migration 0050). mode distinguishes a one-time
    -- snapshot ('clone', detach-snapshot applied at birth) from a subscribed
    -- link ('live', mirror sync keeps it current). NULL = legacy/self-contained.
    source_link_mode     TEXT,
    source_link_consumes TEXT,   -- 'source' | 'target' (null = 'source')
    source_link_gate     TEXT,   -- 'head' | 'validated' (target-consumption only)
    -- Max upstream server_seq (lane-relevant) this project has mirrored.
    source_link_cursor   BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE project_members (
    project_id TEXT NOT NULL,
    user_id    BIGINT NOT NULL,
    role_level INTEGER NOT NULL,
    granted_by BIGINT,
    granted_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (project_id, user_id)
);

CREATE TABLE group_project_grants (
    group_id   BIGINT NOT NULL,
    project_id TEXT NOT NULL,
    role_level INTEGER NOT NULL,
    granted_by BIGINT,
    granted_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (group_id, project_id)
);

CREATE TABLE project_invites (
    token      TEXT NOT NULL,
    project_id TEXT NOT NULL,
    role_level INTEGER NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    expires_at TIMESTAMPTZ,
    used_by    BIGINT,
    used_at    TIMESTAMPTZ,
    email      TEXT,
    PRIMARY KEY (token, project_id)
);

-- Email-based organization invitations (see migrations/0043_org_invites.sql).
CREATE TABLE org_invites (
    token      TEXT PRIMARY KEY,
    org_id     BIGINT NOT NULL,
    role_level INTEGER NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    expires_at TIMESTAMPTZ,
    used_by    BIGINT,
    used_at    TIMESTAMPTZ,
    email      TEXT
);
CREATE INDEX idx_org_invites_org ON org_invites(org_id);
CREATE INDEX idx_org_invites_unused ON org_invites(org_id, used_by) WHERE used_by IS NULL;

CREATE TABLE project_settings (
    project_id TEXT PRIMARY KEY,
    settings   TEXT NOT NULL DEFAULT '{}',
    version    INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by BIGINT,
    -- Language pair extracted from the settings JSON at write time (0054).
    -- settings blobs run to multiple MB; reads must use these columns, never
    -- (settings::jsonb)->>'…' inline (org-dashboard timeout, see
    -- getOrgPortfolio in auth-worker/src/services/org-permissions.ts).
    source_language TEXT GENERATED ALWAYS AS ((settings::jsonb)->>'sourceLanguage') STORED,
    target_language TEXT GENERATED ALWAYS AS ((settings::jsonb)->>'targetLanguage') STORED,
    -- AQU-575: compact portfolio projections. Never load the multi-MB settings
    -- blob merely to read validationCount or targetLanes.
    validation_count TEXT GENERATED ALWAYS AS ((settings::jsonb)->>'validationCount') STORED,
    target_lanes JSONB GENERATED ALWAYS AS ((settings::jsonb)->'targetLanes') STORED
);

CREATE TABLE org_settings (
    org_id     BIGINT PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
    settings   TEXT NOT NULL DEFAULT '{}',
    version    INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by BIGINT REFERENCES users(id)
);

-- Global, runtime-editable platform config (migration 0047). Single row
-- (id = 1), versioned JSON blob like org_settings; read on the chat/agent hot
-- path (cached) with wrangler.toml env vars as fallback. Edited only from the
-- hardened admin console (lib/platform-settings.ts, routes/admin.ts).
CREATE TABLE platform_settings (
    id         INTEGER PRIMARY KEY DEFAULT 1,
    settings   TEXT NOT NULL DEFAULT '{}',
    version    INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by BIGINT REFERENCES users(id),
    CONSTRAINT platform_settings_singleton CHECK (id = 1)
);

-- Step-up "sudo" gate for the admin console (migration 0047).
-- Short-lived 6-digit codes emailed to the operator (clone of
-- password_reset_tokens), single-use; the resulting elevated session lives in
-- admin_elevations (one row per user, expires after ELEVATION_SESSION_HOURS).
CREATE TABLE admin_elevation_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    code       TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_admin_elevation_codes_user ON admin_elevation_codes(user_id);

CREATE TABLE admin_elevations (
    user_id        BIGINT PRIMARY KEY,
    elevated_until TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ DEFAULT now()
);

-- Audit trail for sensitive admin actions (elevation grants, settings edits).
CREATE TABLE admin_audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    action     TEXT NOT NULL,
    detail     TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_admin_audit_log_created ON admin_audit_log(created_at);

-- Org termbase publish/subscribe (migration 0030; terminology Slices 6-7).
-- A subscription row makes `project_id` consume `termbase_project_id`'s
-- published termbase, ordered by `priority` (lower = higher precedence) and
-- confers an implicit viewer read on the upstream termbase project.
CREATE TABLE project_termbase_subscriptions (
    project_id          TEXT    NOT NULL,
    termbase_project_id TEXT    NOT NULL,
    priority            INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (project_id, termbase_project_id)
);
CREATE INDEX idx_termbase_subs_termbase ON project_termbase_subscriptions (termbase_project_id);
CREATE INDEX idx_projects_org_published_termbase ON projects (org_id) WHERE org_published_termbase = TRUE;

-- ───────────────────────── event log + projections ──────────────────────

CREATE TABLE events (
    id             TEXT PRIMARY KEY,
    schema_version INTEGER NOT NULL,
    project_id     TEXT NOT NULL,
    file_id        TEXT,
    cell_id        TEXT,
    kind           TEXT NOT NULL,
    author         TEXT NOT NULL,
    payload        TEXT NOT NULL,
    client_ts      BIGINT NOT NULL,
    server_ts      BIGINT NOT NULL,
    parent_id      TEXT,
    server_seq     BIGINT NOT NULL DEFAULT 0,
    -- AQU-533: server-stamped provenance envelope for externally-originated
    -- events (Agent API). NULL for all internal (in-app / mirror / import)
    -- writes — the canonical event insert never populates it; only the
    -- external changeset commit path stamps it after events land. Shape:
    -- { origin, human_authority:{user_id,credential_id}, agent, channel,
    --   autonomy_mode, changeset_id, confirmation_id? }.
    provenance     JSONB
);

-- Per-project server_seq allocator (audit RACE-1 / M1-1). One row per project,
-- bumped inside the SAME transaction as every events INSERT (see
-- sync-worker/src/events/event-insert.ts): the row lock serializes concurrent
-- same-project writers so two transactions can never compute the same
-- server_seq. Seeded from MAX(events.server_seq) on first use; the bump
-- self-heals if the counter ever falls behind the log (GREATEST against MAX).
-- Gaps in server_seq are possible (idempotent replays still bump) and harmless
-- — server_seq is an ordering key, not a count.
--
-- rebuilt_seq (0036, audit B5): the seq a projection rebuild allocated when
-- it finished. Rebuilds change cells without minting events, so
-- MAX(events.server_seq) — the GET /cells delta/ETag watermark — does not
-- move; any `?since=` cursor below rebuilt_seq is told to resync and the
-- value is folded into the ETag. 0 = never rebuilt.
CREATE TABLE IF NOT EXISTS project_seq_counters (
    project_id  TEXT PRIMARY KEY,
    last_seq    BIGINT NOT NULL,
    rebuilt_seq BIGINT NOT NULL DEFAULT 0
);

-- AD-2 first-child arbitration (audit RACE-2 / M1-1). One row per chain slot
-- (project, file, cell, parent); the first transaction to commit a claim owns
-- the slot, atomically — replacing the check-then-act isWinningChild SELECT
-- for in-flight races. parent_key = parent_id, with '<null>' standing in for
-- genesis events (matches rebuild.ts's in-memory childKey sentinel). The
-- losing sibling's event still lands in `events` (history) but its cells
-- projection write is gated on holding the claim.
CREATE TABLE IF NOT EXISTS chain_claims (
    project_id TEXT NOT NULL,
    file_id    TEXT NOT NULL,
    cell_id    TEXT NOT NULL,
    parent_key TEXT NOT NULL,
    event_id   TEXT NOT NULL,
    PRIMARY KEY (project_id, file_id, cell_id, parent_key)
);

CREATE TABLE files (
    id             TEXT PRIMARY KEY,
    project_id     TEXT NOT NULL,
    name           TEXT NOT NULL,
    role           TEXT,
    kind           TEXT,
    book_code      TEXT,
    source_file_id TEXT,
    anchor_file_id TEXT,
    event_id       TEXT NOT NULL,
    cell_count     INTEGER NOT NULL DEFAULT 0,
    approved_count INTEGER NOT NULL DEFAULT 0,
    word_count     INTEGER NOT NULL DEFAULT 0,
    last_edit_at   BIGINT,
    created_by     TEXT,
    created_at     BIGINT,
    updated_at     BIGINT,
    meta           TEXT NOT NULL DEFAULT '{}',
    filled_count   INTEGER NOT NULL DEFAULT 0,
    -- AQU-272: soft-delete tombstone. NULL = active; epoch-ms = tombstoned.
    -- Cells + audio retained; R2 wipe deferred (see migration 0036).
    deleted_at     BIGINT DEFAULT NULL,
    -- AQU-292: target cells currently marked ai_drafted=1 (machine-drafted, not yet
    -- human-edited or validated). Recomputed by fileCountersRecomputeStmt on every
    -- target.cell.commit or cell.validate projection. Forward-only: 0 for all cells
    -- predating migration 0037.
    ai_drafted_count INTEGER NOT NULL DEFAULT 0,
    UNIQUE (id, project_id)
);

CREATE TABLE cells (
    project_id        TEXT NOT NULL,
    file_id           TEXT NOT NULL,
    cell_id           TEXT NOT NULL,
    side              TEXT NOT NULL CHECK (side IN ('source', 'target')),
    value             TEXT NOT NULL,
    value_html        TEXT,
    type              TEXT,
    canonical_ref     TEXT,
    anchor_cell_id    TEXT,
    event_id          TEXT NOT NULL,
    source_event_id   TEXT,
    last_editor       TEXT,
    last_edit_at      BIGINT NOT NULL,
    validated         INTEGER NOT NULL DEFAULT 0,
    word_count        INTEGER NOT NULL DEFAULT 0,
    content_hash      TEXT,
    endorsement_count INTEGER NOT NULL DEFAULT 0,
    -- AQU-292: 1 when this target cell was machine-drafted (ai_suggestion=true on the
    -- committing event) and has not yet been human-edited or validated. Cleared to 0
    -- by any subsequent human target.cell.commit or cell.validate. Forward-only:
    -- historical commits without the ai_suggestion field default to 0.
    ai_drafted        INTEGER NOT NULL DEFAULT 0,
    start_ms          BIGINT,
    end_ms            BIGINT,
    medium            TEXT,
    sequence_index    DOUBLE PRECISION,
    transcription     TEXT,
    camera_state      TEXT,
    -- OBS parity (0045): extensible per-cell metadata bucket. Mirrors the
    -- extensible source.cell.create payload.metadata. Holds e.g.
    -- { "attachments": [{ "type": "image", "url": "…", "alt": "…" }] };
    -- future keys (gif/video/audio attachments, etc.) need no schema change.
    metadata          JSONB,
    source_location   TEXT,
    -- AQU-476: mirror provenance (migration 0050). Set on a downstream's
    -- source-side row by source.cell.mirror — the upstream event id/seq this
    -- row currently reflects (monotonic apply-guard key, see link-sync.ts) and,
    -- if the upstream deleted the cell, when this row was tombstoned (never
    -- actually deleted — see the linked-projects design spec §5).
    upstream_event_id TEXT,
    upstream_seq      BIGINT,
    tombstoned_at     BIGINT,
    -- AQU-538: target-language lane (migration 0054). '' = the file's single
    -- configured target language (every pre-lane row, and the default lane for
    -- projects that never add a second language — N=1 back-compat). Source-side
    -- rows are ALWAYS '' (the source is shared by all lanes; that is the point
    -- of the TMS-style model). Non-'' lanes are BCP-47-ish tags chosen by the
    -- add-a-language flow; the projection treats the value as opaque.
    target_lang       TEXT NOT NULL DEFAULT '',
    -- Replaces SQLite FTS5. Maintained automatically; no triggers needed.
    value_tsv         tsvector GENERATED ALWAYS AS (to_tsvector('simple', value)) STORED,
    PRIMARY KEY (project_id, file_id, cell_id, side, target_lang)
);

-- AQU-517: compact derived progress. One file row plus one row per meaningful
-- canonical section; validator_histogram keys are exact endorsement counts,
-- capped at 15 (the 15 key means 15+).
CREATE TABLE file_section_progress (
    project_id          TEXT NOT NULL,
    file_id             TEXT NOT NULL,
    scope               TEXT NOT NULL CHECK (scope IN ('file', 'section')),
    section_key         TEXT NOT NULL DEFAULT '',
    target_lang         TEXT NOT NULL DEFAULT '',
    total_count         INTEGER NOT NULL DEFAULT 0 CHECK (total_count >= 0),
    filled_count        INTEGER NOT NULL DEFAULT 0 CHECK (filled_count >= 0),
    validator_histogram JSONB NOT NULL DEFAULT '{}'::jsonb,
    revision            BIGINT NOT NULL DEFAULT 0,
    updated_at          BIGINT NOT NULL,
    PRIMARY KEY (project_id, file_id, scope, section_key, target_lang),
    CHECK (
      (scope = 'file' AND section_key = '') OR
      (scope = 'section' AND section_key <> '')
    )
);

CREATE INDEX idx_file_section_progress_file_revision ON file_section_progress(project_id, file_id, revision);

CREATE TABLE cell_validators (
    project_id  TEXT NOT NULL,
    file_id     TEXT NOT NULL,
    cell_id     TEXT NOT NULL,
    target_lang TEXT NOT NULL DEFAULT '',
    event_id    TEXT NOT NULL,
    username    TEXT NOT NULL,
    decided_ts  BIGINT NOT NULL,
    PRIMARY KEY (project_id, file_id, cell_id, target_lang, username)
);

CREATE TABLE cell_waivers (
    project_id TEXT NOT NULL,
    file_id    TEXT NOT NULL,
    cell_id    TEXT NOT NULL,
    rule_id    TEXT NOT NULL,
    reason     TEXT,
    waived_by  TEXT NOT NULL,
    waived_ts  BIGINT NOT NULL,
    PRIMARY KEY (project_id, file_id, cell_id, rule_id)
);

CREATE TABLE cell_audio (
    project_id         TEXT NOT NULL,
    file_id            TEXT NOT NULL,
    cell_id            TEXT NOT NULL,
    audio_id           TEXT NOT NULL,
    slot               TEXT NOT NULL,
    url                TEXT NOT NULL,
    mime_type          TEXT,
    voice_id           TEXT,
    reference_audio_id TEXT,
    duration_ms        BIGINT,
    timings_json       TEXT,
    selected           INTEGER NOT NULL DEFAULT 0,
    deleted            INTEGER NOT NULL DEFAULT 0,
    event_id           TEXT NOT NULL,
    created_ts         BIGINT NOT NULL,
    trim_start_ms      BIGINT,
    trim_end_ms        BIGINT,
    -- AQU-508: audio validation, distinct from text validation (cells.validated).
    -- A reviewer approves the *selected* clip of a cell via cell.audio.validate;
    -- cell.audio.unvalidate clears it. The audio-validated rollup counts cells
    -- whose selected, live clip is approved (deleted = 0 AND selected = 1 AND
    -- approved = 1) — so re-recording (which selects a new clip) drops the cell
    -- back to "needs re-validation" until the new take is approved.
    approved           INTEGER NOT NULL DEFAULT 0,
    approved_by        TEXT,
    approved_ts        BIGINT,
    PRIMARY KEY (project_id, file_id, cell_id, audio_id)
);

CREATE TABLE cell_backtranslations (
    project_id      TEXT NOT NULL,
    file_id         TEXT NOT NULL,
    cell_id         TEXT NOT NULL,
    target_event_id TEXT NOT NULL,
    bt_text         TEXT NOT NULL,
    bt_html         TEXT,
    polished        INTEGER NOT NULL DEFAULT 0,
    author          TEXT NOT NULL,
    event_id        TEXT NOT NULL,
    server_seq      BIGINT,
    created_at      BIGINT NOT NULL,
    PRIMARY KEY (project_id, file_id, cell_id, target_event_id)
);

CREATE TABLE comments (
    comment_id        TEXT PRIMARY KEY,
    project_id        TEXT NOT NULL,
    scope_kind        TEXT NOT NULL,
    file_id           TEXT,
    cell_id           TEXT,
    parent_comment_id TEXT,
    body              TEXT NOT NULL,
    resolved          INTEGER NOT NULL DEFAULT 0,
    author_id         TEXT NOT NULL,
    author_label      TEXT,
    created_at        BIGINT NOT NULL,
    updated_at        BIGINT NOT NULL,
    deleted_at        BIGINT
);

-- ─────────────────────────── assignments + misc ─────────────────────────

CREATE TABLE assignments (
    assignment_id    TEXT PRIMARY KEY,
    project_id       TEXT NOT NULL,
    assignee_user_id BIGINT NOT NULL,
    scope_kind       TEXT NOT NULL,
    scope_label      TEXT NOT NULL,
    -- AQU-538 (§3.5 / migration 0057): target-language lane this assignment is
    -- pinned to. '' = the default lane (every pre-lane assignment). Not part of
    -- the PK — assignment_id stays the key; a lane is a property of the unit.
    target_lang      TEXT NOT NULL DEFAULT '',
    cells_total      INTEGER NOT NULL DEFAULT 0,
    deadline         TEXT,
    note             TEXT,
    created_by       BIGINT NOT NULL,
    created_at       BIGINT NOT NULL,
    unassigned_at    BIGINT,
    completed_at     BIGINT
);

CREATE TABLE assignment_cells (
    assignment_id TEXT NOT NULL,
    file_id       TEXT NOT NULL,
    cell_id       TEXT NOT NULL,
    PRIMARY KEY (assignment_id, file_id, cell_id)
);

CREATE TABLE diarization_jobs (
    id           TEXT PRIMARY KEY,
    project_id   TEXT NOT NULL,
    file_id      TEXT NOT NULL,
    audio_object TEXT NOT NULL,
    fetch_token  TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'queued',
    num_speakers INTEGER,
    turns_json   TEXT,
    error        TEXT,
    created_at   BIGINT NOT NULL,
    updated_at   BIGINT NOT NULL
);

CREATE TABLE file_source_blobs (
    file_id    TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    format     TEXT NOT NULL,
    raw_source TEXT,
    r2_key     TEXT,
    size_bytes BIGINT,
    created_at BIGINT NOT NULL
);

CREATE TABLE checkpoints (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    file_id    TEXT NOT NULL,
    label      TEXT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    r2_key     TEXT NOT NULL
);

-- Migration 0032: per-word morphology for Macula Hebrew + Greek (AQU-178)
CREATE TABLE cell_word_morph (
    project_id  TEXT NOT NULL,
    file_id     TEXT NOT NULL,
    cell_id     TEXT NOT NULL,
    word_seq    INTEGER NOT NULL,   -- 1-based position within the cell
    surface     TEXT NOT NULL,      -- surface form as it appears in the text
    lemma       TEXT,               -- dictionary lemma
    morph_code  TEXT,               -- morphology code (e.g. Macula/OSHB/Robinson format)
    strongs_h   TEXT,               -- Strong's Hebrew number (e.g. H1234), NULL for Greek
    strongs_g   TEXT,               -- Strong's Greek number (e.g. G1234), NULL for Hebrew
    PRIMARY KEY (project_id, file_id, cell_id, word_seq)
);

-- ────────────────────────────── indexes ─────────────────────────────────

CREATE INDEX idx_activity_logs_timestamp ON activity_logs(timestamp);
CREATE INDEX idx_activity_logs_user_id ON activity_logs(user_id);
CREATE INDEX assignment_cells_by_assignment ON assignment_cells(assignment_id);
CREATE INDEX assignments_assignee ON assignments(assignee_user_id);
CREATE INDEX assignments_project ON assignments(project_id);
CREATE INDEX idx_cell_audio_file ON cell_audio(project_id, file_id) WHERE deleted = 0;
CREATE INDEX idx_cell_word_morph_file ON cell_word_morph(project_id, file_id);
CREATE INDEX idx_cell_word_morph_lemma ON cell_word_morph(lemma) WHERE lemma IS NOT NULL;
CREATE INDEX idx_cell_bt_cell ON cell_backtranslations(project_id, file_id, cell_id, created_at DESC);
CREATE INDEX idx_cell_bt_file ON cell_backtranslations(project_id, file_id);
CREATE INDEX idx_cell_validators_cell ON cell_validators(project_id, file_id, cell_id);
CREATE INDEX idx_cell_waivers_file ON cell_waivers(project_id, file_id);
CREATE INDEX idx_cells_decay_drags ON cells(project_id, endorsement_count);
CREATE INDEX idx_cells_file_order ON cells(project_id, file_id, side, anchor_cell_id);
CREATE INDEX idx_cells_last_edit ON cells(project_id, file_id, side, last_edit_at);
CREATE INDEX idx_cells_pair_lookup ON cells(project_id, cell_id, side);
CREATE INDEX idx_cells_source_basis ON cells(source_event_id);
CREATE INDEX idx_cells_validated ON cells(project_id, file_id, side, validated);
-- AQU-476: mirror provenance lookup (only mirrored rows carry this).
CREATE INDEX idx_cells_upstream_event ON cells(upstream_event_id) WHERE upstream_event_id IS NOT NULL;
-- FTS replacement: GIN over the generated tsvector.
CREATE INDEX idx_cells_value_tsv ON cells USING GIN (value_tsv);
CREATE INDEX idx_checkpoints_file ON checkpoints(file_id, created_at);
CREATE INDEX idx_checkpoints_project ON checkpoints(project_id, created_at);
CREATE INDEX comments_project_scope ON comments(project_id, scope_kind, file_id, cell_id);
CREATE INDEX comments_thread ON comments(project_id, parent_comment_id);
CREATE INDEX idx_diarization_jobs_file ON diarization_jobs(project_id, file_id);
CREATE INDEX idx_events_author ON events(author, server_ts);
CREATE INDEX idx_events_cell ON events(project_id, file_id, cell_id, server_ts);
CREATE INDEX idx_events_file_seq ON events(project_id, file_id, server_seq);
CREATE INDEX idx_events_parent_lookup ON events(project_id, file_id, cell_id, parent_id);
CREATE INDEX idx_events_project ON events(project_id, server_ts);
CREATE UNIQUE INDEX idx_events_project_seq ON events(project_id, server_seq);
CREATE INDEX idx_file_source_blobs_project ON file_source_blobs(project_id);
CREATE INDEX idx_files_anchor_file ON files(anchor_file_id) WHERE anchor_file_id IS NOT NULL;
CREATE INDEX idx_files_last_edit ON files(project_id, last_edit_at);
CREATE INDEX idx_files_project ON files(project_id);
CREATE INDEX idx_files_project_role ON files(project_id, role) WHERE role IS NOT NULL;
CREATE INDEX idx_files_source_file ON files(source_file_id) WHERE source_file_id IS NOT NULL;
CREATE INDEX idx_files_project_active ON files(project_id, deleted_at NULLS FIRST);
CREATE INDEX idx_group_members_user ON group_members(user_id);
CREATE INDEX idx_gpg_project ON group_project_grants(project_id);
CREATE UNIQUE INDEX idx_groups_legacy_uuid ON groups(legacy_uuid);
CREATE INDEX idx_groups_org ON groups(org_id);
CREATE INDEX idx_org_members_org ON org_members(org_id);
CREATE INDEX idx_org_members_user ON org_members(user_id);
CREATE UNIQUE INDEX idx_organizations_legacy_uuid ON organizations(legacy_uuid);
CREATE INDEX idx_organizations_owner ON organizations(owner_user_id);
CREATE INDEX idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX idx_project_invites_project ON project_invites(project_id);
CREATE INDEX idx_project_invites_token ON project_invites(token);
CREATE INDEX idx_project_invites_unused ON project_invites(project_id, used_by) WHERE used_by IS NULL;
CREATE INDEX idx_project_members_user ON project_members(user_id);
CREATE INDEX idx_project_settings_updated_at ON project_settings(updated_at);
CREATE INDEX idx_projects_archived ON projects(archived_at) WHERE archived_at IS NOT NULL;
CREATE INDEX idx_projects_created_by ON projects(created_by);
CREATE INDEX idx_projects_org ON projects(org_id);
CREATE INDEX idx_projects_source_project ON projects(source_project_id) WHERE source_project_id IS NOT NULL;
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);

-- AQU-265: AI budget counters (0034_ai_usage_daily.sql)
CREATE TABLE IF NOT EXISTS ai_usage_daily (
  user_id       INTEGER     NOT NULL,
  date_utc      DATE        NOT NULL,
  request_count INTEGER     NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, date_utc)
);
CREATE INDEX IF NOT EXISTS idx_ai_usage_daily_date ON ai_usage_daily(date_utc);

-- OmniVoice TTS usage metering (0041_tts_usage_daily.sql).
-- Per-user, org-attributed audio-seconds. (user_id=0, org_id=0) = global sentinel.
-- Org totals derived at read time: SUM WHERE org_id = ?
CREATE TABLE IF NOT EXISTS tts_usage_daily (
  user_id       INTEGER          NOT NULL,
  org_id        INTEGER          NOT NULL,
  date_utc      DATE             NOT NULL,
  request_count INTEGER          NOT NULL DEFAULT 0,
  audio_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, org_id, date_utc)
);
CREATE INDEX IF NOT EXISTS idx_tts_usage_org_date ON tts_usage_daily (org_id, date_utc);

-- Org credits & unified compute-cost model (0042_org_credit_usage_daily.sql).
-- Cross-rail cost rollup; rail = 'llm' | 'agent' | 'tts'. raw_cost_cents = actual
-- infra cost; credits derived on read. Existing usage tables unchanged.
CREATE TABLE IF NOT EXISTS org_credit_usage_daily (
  org_id         INTEGER          NOT NULL,
  user_id        INTEGER          NOT NULL,
  date_utc       DATE             NOT NULL,
  rail           TEXT             NOT NULL,
  raw_cost_cents DOUBLE PRECISION NOT NULL DEFAULT 0,
  units          INTEGER          NOT NULL DEFAULT 0,
  PRIMARY KEY (org_id, user_id, date_utc, rail)
);
CREATE INDEX IF NOT EXISTS idx_org_credit_org_date ON org_credit_usage_daily (org_id, date_utc);

-- Translation agent run ledger (0040_agent_runs.sql). One row per
-- POST /api/v1/ai/agent/run; staged commits carry payload.agent_run_id →
-- run_id for attribution / undo-run / cost rollups.
CREATE TABLE IF NOT EXISTS agent_runs (
    run_id      TEXT PRIMARY KEY,
    project_id  TEXT NOT NULL,
    user_id     BIGINT NOT NULL,
    username    TEXT NOT NULL,
    prompt      TEXT NOT NULL,
    model       TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'running', -- running|ok|capped|error
    prompt_tokens     BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    cost_cents  DOUBLE PRECISION NOT NULL DEFAULT 0,
    steps       INTEGER NOT NULL DEFAULT 0,
    session_id  TEXT,                            -- 0050: owning agent_sessions row (nullable)
    staged_count INTEGER NOT NULL DEFAULT 0,     -- 0051: target.cell.commit events staged by the run
    started_at  BIGINT NOT NULL,
    ended_at    BIGINT
);
CREATE INDEX IF NOT EXISTS idx_agent_runs_project ON agent_runs (project_id, started_at DESC);

-- Agent sessions (0050_agent_sessions.sql): server-persisted conversations for
-- the translation agent. convo = JSON array of stored messages (user/assistant/
-- tool — the system prompt is rebuilt per run). Session ids are client-generated
-- UUIDs; ownership is (project_id, user_id), enforced on load.
CREATE TABLE IF NOT EXISTS agent_sessions (
    session_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    user_id    BIGINT NOT NULL,
    title      TEXT NOT NULL DEFAULT '',
    convo      TEXT NOT NULL DEFAULT '[]',
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_project_user
    ON agent_sessions (project_id, user_id, updated_at DESC);

-- Model A/B testing (0048_model_ab_events.sql). One row per default-model chat
-- request while a platform experiment (platform_settings.abTest) is enabled;
-- arm = champion (defaultLlmModel) | challenger. The SPA reports the user's
-- gesture on the AI output (accepted = cell validated, edited = human commit
-- overwrote the draft) via POST /chat/ab-feedback keyed by the id returned in
-- the X-AB-Request-Id response header. Aggregated by GET /admin/ab-results.
CREATE TABLE IF NOT EXISTS model_ab_events (
    id         TEXT PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    arm        TEXT NOT NULL,                 -- 'champion' | 'challenger'
    model      TEXT NOT NULL,
    source     TEXT NOT NULL DEFAULT 'chat',
    error      INTEGER NOT NULL DEFAULT 0,    -- 1 = upstream request failed
    latency_ms INTEGER,
    outcome    TEXT,                          -- 'accepted' | 'edited' | 'rejected'
    -- 0049: normalized Levenshtein [0,1] between the AI draft and the human's
    -- text — 0 = accepted verbatim. Outcome is first-write-wins; the distance
    -- refines with further edits (last write wins).
    edit_distance DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    outcome_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_model_ab_events_created ON model_ab_events(created_at);
CREATE INDEX IF NOT EXISTS idx_model_ab_events_user ON model_ab_events(user_id);

-- Lane-scoped reviewer permissions (0059_project_member_scopes.sql, AQU-553).
-- ADDITIVE restrictions on a member's role floor. No rows for a (project,user)
-- pair = unscoped = today's behavior. 'lane' rows restrict target-side writes
-- to those lanes (default lane stored as literal ''); 'file' rows restrict
-- writes to those fileIds. Kinds compose with AND. Enforced in sync-worker
-- authorize; source/comment/audio/file-level events are never gated. Leads
-- (role >= 500) must stay unscoped (auth-worker CRUD rejects scoping them).
CREATE TABLE IF NOT EXISTS project_member_scopes (
    project_id TEXT NOT NULL,
    user_id    BIGINT NOT NULL,
    kind       TEXT NOT NULL CHECK (kind IN ('lane','file')),
    value      TEXT NOT NULL,
    created_by TEXT,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (project_id, user_id, kind, value)
);

-- AQU-533 Agent API: immutable changeset execution plans (0055). External
-- callers submit domain commands; prepare compiles them into a staged plan
-- with server-computed preconditions, effect summary, and content digest.
-- Commit re-checks preconditions (plan_stale on drift), routes compiled events
-- through the existing /events perimeter, and records an execution receipt.
CREATE TABLE IF NOT EXISTS changesets (
    id                 TEXT PRIMARY KEY,          -- client-supplied UUIDv7
    project_id         TEXT NOT NULL,
    created_by_user_id TEXT NOT NULL,             -- the credential's owning user
    credential_id      TEXT NOT NULL,
    autonomy_mode      TEXT NOT NULL CHECK (autonomy_mode IN ('ask', 'act')),
    status             TEXT NOT NULL DEFAULT 'staged'
                         CHECK (status IN ('staged', 'committing', 'committed', 'discarded', 'stale', 'expired')),
    commands           JSONB NOT NULL,            -- normalized domain commands
    preconditions      JSONB NOT NULL,            -- per-cell head/source pins resolved at prepare
    summary            JSONB NOT NULL,            -- server-computed effect summary
    digest             TEXT NOT NULL,             -- SHA-256 over canonical(commands + preconditions)
    receipt            JSONB,                     -- execution receipt (after commit)
    confirmation_id    TEXT,                      -- consumed ask-mode approval (after commit)
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at         TIMESTAMPTZ NOT NULL,
    committed_at       TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_changesets_project_status ON changesets(project_id, status);

-- One-time human approval assertions for ask-mode commits (AQU-533 §3). A row
-- binds a specific changeset digest + credential; commit consumes it exactly
-- once (UPDATE ... SET consumed_at WHERE consumed_at IS NULL RETURNING).
CREATE TABLE IF NOT EXISTS changeset_confirmations (
    id            TEXT PRIMARY KEY,               -- UUIDv7
    changeset_id  TEXT NOT NULL,
    user_id       TEXT NOT NULL,                  -- approving human (browser session)
    credential_id TEXT NOT NULL,
    digest        TEXT NOT NULL,                  -- must match the changeset digest at commit
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ NOT NULL,
    consumed_at   TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_changeset_confirmations_changeset
  ON changeset_confirmations(changeset_id);

-- External API credentials (0054_api_credentials.sql): personal access tokens
-- for the Agent API (AQU-533 §2). Per-user, optionally scoped to an org and/or
-- project, with an autonomy ceiling ('ask' | 'act'). Only a SHA-256 hash is
-- stored; token_prefix (first 12 chars, incl. the 'aqk_' tag) is display-only.
-- User-scoped like agent_sessions; live role is re-resolved per call.
CREATE TABLE IF NOT EXISTS api_credentials (
    id           UUID PRIMARY KEY,
    user_id      TEXT NOT NULL,
    name         TEXT NOT NULL,
    token_prefix TEXT NOT NULL,
    token_hash   TEXT NOT NULL UNIQUE,
    mode         TEXT NOT NULL CHECK (mode IN ('ask', 'act')),
    org_id       TEXT,
    project_id   TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_api_credentials_user ON api_credentials(user_id);
CREATE INDEX IF NOT EXISTS idx_api_credentials_token_hash ON api_credentials(token_hash);

-- Uploaded source artifacts (0056_artifacts.sql): agent-uploaded original files
-- (USFM, JSON, XLIFF, …) preserved verbatim in R2 for round-trip fidelity and
-- format inspection (AQU-533 §5). Bytes live in SNAPSHOTS under
-- `{prefix}artifacts/{projectId}/{artifactId}`; this row is metadata +
-- provenance + integrity digest. `file_id` is linked when a PlanImport
-- changeset referencing the artifact commits.
--
-- 0064_artifacts_audio.sql (Agent API v1.1 §3, W2-B): `kind` distinguishes a
-- verbatim source artifact ('source') from an uploaded audio clip ('audio').
-- Audio bytes are stored in the EXISTING per-file audio R2 layout used by
-- audio.ts (`{prefix}projects/{projectId}/files/{artifactId}/audio/{audio_id}`)
-- so a LinkMedia commit can serve them through the app's native /audio route;
-- `audio_id` is the full object name (`<artifactId>.<ext>`) the audio layout +
-- the cell.audio.attach payload expect.
CREATE TABLE IF NOT EXISTS artifacts (
    id                  UUID PRIMARY KEY,
    project_id          TEXT NOT NULL,
    uploaded_by_user_id TEXT NOT NULL,
    credential_id       TEXT NOT NULL,
    name                TEXT NOT NULL,
    content_type        TEXT,
    size_bytes          BIGINT NOT NULL,
    sha256              TEXT NOT NULL,
    r2_key              TEXT NOT NULL,
    file_id             TEXT,
    kind                TEXT NOT NULL DEFAULT 'source',
    audio_id            TEXT,
    -- AQU-635: format inspection/classification facts that belong to the
    -- immutable artifact rather than any one file interpretation.
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id, project_id)
);
CREATE INDEX IF NOT EXISTS idx_artifacts_project ON artifacts(project_id);

-- AQU-635: one immutable artifact can contribute multiple package members or
-- files. Per-cell reversible locators remain in cells.metadata; this relation
-- stores only file-level interpretation/provenance and compact manifests.
CREATE TABLE IF NOT EXISTS artifact_bindings (
    id              UUID PRIMARY KEY,
    project_id      TEXT NOT NULL,
    artifact_id     UUID NOT NULL,
    file_id         TEXT NOT NULL,
    binding_role    TEXT NOT NULL
                      CHECK (binding_role IN ('source', 'target', 'support', 'roundtrip-output')),
    target_lang     TEXT NOT NULL DEFAULT '',
    member_path     TEXT NOT NULL DEFAULT '',
    profile_id      TEXT NOT NULL,
    profile_version TEXT NOT NULL,
    fidelity        TEXT NOT NULL
                      CHECK (fidelity IN ('native', 'verified-recipe', 'content-only', 'preserved-only')),
    manifest        JSONB NOT NULL DEFAULT '{}'::jsonb,
    recipe          JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (artifact_id, file_id, binding_role, target_lang, member_path),
    CONSTRAINT artifact_bindings_artifact_project_fkey
      FOREIGN KEY (artifact_id, project_id)
      REFERENCES artifacts(id, project_id)
      ON DELETE CASCADE,
    CONSTRAINT artifact_bindings_file_project_fkey
      FOREIGN KEY (file_id, project_id)
      REFERENCES files(id, project_id)
      ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_artifact_bindings_project_file
  ON artifact_bindings(project_id, file_id);
CREATE INDEX IF NOT EXISTS idx_artifact_bindings_artifact
  ON artifact_bindings(artifact_id);

-- ───────────────────────── post-migration notes ─────────────────────────
-- After the bulk data load (Stage C), reset each identity sequence so new
-- inserts don't collide with migrated ids:
--   SELECT setval(pg_get_serial_sequence('users','id'),         COALESCE((SELECT MAX(id) FROM users),1));
--   SELECT setval(pg_get_serial_sequence('organizations','id'), COALESCE((SELECT MAX(id) FROM organizations),1));
--   SELECT setval(pg_get_serial_sequence('groups','id'),        COALESCE((SELECT MAX(id) FROM groups),1));
--   SELECT setval(pg_get_serial_sequence('activity_logs','id'), COALESCE((SELECT MAX(id) FROM activity_logs),1));
--   SELECT setval(pg_get_serial_sequence('password_reset_tokens','id'), COALESCE((SELECT MAX(id) FROM password_reset_tokens),1));
