-- Aquilla Postgres schema — ported from Cloudflare D1 (SQLite).
-- Target: Neon Postgres 18, reached from Workers via Hyperdrive.
--
-- Translation rules (see docs/design/storage-migration-d1-to-neon.md):
--   • INTEGER PRIMARY KEY AUTOINCREMENT  -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--       (BY DEFAULT so the data migration can insert existing ids; reset the
--        identity sequence afterwards — see the bottom of this file.)
--   • STRICT / WITHOUT ROWID             -> removed (Postgres has neither)
--   • DATETIME DEFAULT CURRENT_TIMESTAMP -> TIMESTAMPTZ DEFAULT now()
--   • epoch-millisecond INTEGER columns  -> BIGINT
--   • REAL                               -> DOUBLE PRECISION
--   • 0/1 flag columns                   -> kept as INTEGER (app reads 0/1 — no app change)
--   • JSON-in-text (payload/settings/meta/preferences/…) -> kept as TEXT (app does JSON.parse)
--   • SQLite FTS5 (cells_fts + 3 sync triggers) -> a generated `value_tsv` tsvector
--       column on `cells` + a GIN index. 'simple' config (no stemming) because the
--       corpus is multilingual Bible text.
--   • FOREIGN KEY constraints are INTENTIONALLY OMITTED. SQLite ships with FK
--       enforcement OFF by default, so D1 never enforced these and the live data may
--       violate them; recreating them here would fail the bulk data load. PRIMARY KEY,
--       UNIQUE and CHECK (which SQLite DID enforce) are preserved. Add FKs later, once
--       the migrated data is verified clean, as DEFERRABLE constraints.
--
-- Excluded D1-internal/derived tables: _cf_KV, d1_migrations, cells_fts*.

-- ─────────────────────────────── identity ───────────────────────────────

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT UNIQUE NOT NULL,
    email         TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    preferences   TEXT NOT NULL DEFAULT '{}',
    created_at    TIMESTAMPTZ DEFAULT now(),
    updated_at    TIMESTAMPTZ DEFAULT now(),
    display_name  TEXT,
    avatar_url    TEXT,
    email_verified_at TIMESTAMPTZ
);

CREATE TABLE organizations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT,
    owner_user_id BIGINT NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT now(),
    updated_at    TIMESTAMPTZ DEFAULT now(),
    legacy_uuid   TEXT
);

CREATE TABLE org_members (
    org_id         BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    role_level     INTEGER NOT NULL,
    granted_by     BIGINT,
    granted_at     TIMESTAMPTZ DEFAULT now(),
    last_active_at TIMESTAMPTZ,
    PRIMARY KEY (org_id, user_id)
);

CREATE TABLE groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT NOT NULL,
    name        TEXT NOT NULL,
    description TEXT,
    created_by  BIGINT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ DEFAULT now(),
    legacy_uuid TEXT,
    is_internal BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (org_id, name)
);

CREATE TABLE group_members (
    group_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    added_by BIGINT,
    added_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (group_id, user_id)
);

CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token      TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Soft email verification (see migrations/0044_email_verification.sql).
CREATE TABLE email_verification_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token      TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_email_verification_tokens_token ON email_verification_tokens(token);

CREATE TABLE activity_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    activity_type     TEXT,
    description       TEXT,
    activity_metadata TEXT,
    timestamp         TIMESTAMPTZ DEFAULT now()
);

-- ─────────────────────────────── projects ───────────────────────────────

CREATE TABLE projects (
    id                TEXT PRIMARY KEY,
    name              TEXT NOT NULL,
    org_id            BIGINT,
    created_by        BIGINT NOT NULL,
    created_at        TIMESTAMPTZ DEFAULT now(),
    updated_at        TIMESTAMPTZ DEFAULT now(),
    archived_at       TIMESTAMPTZ,
    archived_by       BIGINT,
    source_project_id TEXT,
    deadline_at       TEXT,         -- calendar date string 'YYYY-MM-DD' (not an instant; TIMESTAMPTZ would TZ-shift it)
    -- Org termbase publish flag (migration 0030). TRUE = this project's termbase
    -- is discoverable by other projects in its org.
    org_published_termbase BOOLEAN NOT NULL DEFAULT FALSE,
    -- Active/inactive lifecycle flag (migration 0033). FALSE = frozen/dormant;
    -- deliberate reactivation required to edit. DISTINCT from archived_at
    -- (Trash): inactive projects remain visible in the list but block edits.
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE project_members (
    project_id TEXT NOT NULL,
    user_id    BIGINT NOT NULL,
    role_level INTEGER NOT NULL,
    granted_by BIGINT,
    granted_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (project_id, user_id)
);

CREATE TABLE group_project_grants (
    group_id   BIGINT NOT NULL,
    project_id TEXT NOT NULL,
    role_level INTEGER NOT NULL,
    granted_by BIGINT,
    granted_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (group_id, project_id)
);

CREATE TABLE project_invites (
    token      TEXT NOT NULL,
    project_id TEXT NOT NULL,
    role_level INTEGER NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    expires_at TIMESTAMPTZ,
    used_by    BIGINT,
    used_at    TIMESTAMPTZ,
    email      TEXT,
    PRIMARY KEY (token, project_id)
);

-- Email-based organization invitations (see migrations/0043_org_invites.sql).
CREATE TABLE org_invites (
    token      TEXT PRIMARY KEY,
    org_id     BIGINT NOT NULL,
    role_level INTEGER NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    expires_at TIMESTAMPTZ,
    used_by    BIGINT,
    used_at    TIMESTAMPTZ,
    email      TEXT
);
CREATE INDEX idx_org_invites_org ON org_invites(org_id);
CREATE INDEX idx_org_invites_unused ON org_invites(org_id, used_by) WHERE used_by IS NULL;

CREATE TABLE project_settings (
    project_id TEXT PRIMARY KEY,
    settings   TEXT NOT NULL DEFAULT '{}',
    version    INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by BIGINT
);

CREATE TABLE org_settings (
    org_id     BIGINT PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
    settings   TEXT NOT NULL DEFAULT '{}',
    version    INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by BIGINT REFERENCES users(id)
);

-- Global, runtime-editable platform config (migration 0047). Single row
-- (id = 1), versioned JSON blob like org_settings; read on the chat/agent hot
-- path (cached) with wrangler.toml env vars as fallback. Edited only from the
-- hardened admin console (lib/platform-settings.ts, routes/admin.ts).
CREATE TABLE platform_settings (
    id         INTEGER PRIMARY KEY DEFAULT 1,
    settings   TEXT NOT NULL DEFAULT '{}',
    version    INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by BIGINT REFERENCES users(id),
    CONSTRAINT platform_settings_singleton CHECK (id = 1)
);

-- Step-up "sudo" gate for the admin console (migration 0047).
-- Short-lived 6-digit codes emailed to the operator (clone of
-- password_reset_tokens), single-use; the resulting elevated session lives in
-- admin_elevations (one row per user, expires after ELEVATION_SESSION_HOURS).
CREATE TABLE admin_elevation_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    code       TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_admin_elevation_codes_user ON admin_elevation_codes(user_id);

CREATE TABLE admin_elevations (
    user_id        BIGINT PRIMARY KEY,
    elevated_until TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ DEFAULT now()
);

-- Audit trail for sensitive admin actions (elevation grants, settings edits).
CREATE TABLE admin_audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    action     TEXT NOT NULL,
    detail     TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_admin_audit_log_created ON admin_audit_log(created_at);

-- Org termbase publish/subscribe (migration 0030; terminology Slices 6-7).
-- A subscription row makes `project_id` consume `termbase_project_id`'s
-- published termbase, ordered by `priority` (lower = higher precedence) and
-- confers an implicit viewer read on the upstream termbase project.
CREATE TABLE project_termbase_subscriptions (
    project_id          TEXT    NOT NULL,
    termbase_project_id TEXT    NOT NULL,
    priority            INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (project_id, termbase_project_id)
);
CREATE INDEX idx_termbase_subs_termbase ON project_termbase_subscriptions (termbase_project_id);
CREATE INDEX idx_projects_org_published_termbase ON projects (org_id) WHERE org_published_termbase = TRUE;

-- ───────────────────────── event log + projections ──────────────────────

CREATE TABLE events (
    id             TEXT PRIMARY KEY,
    schema_version INTEGER NOT NULL,
    project_id     TEXT NOT NULL,
    file_id        TEXT,
    cell_id        TEXT,
    kind           TEXT NOT NULL,
    author         TEXT NOT NULL,
    payload        TEXT NOT NULL,
    client_ts      BIGINT NOT NULL,
    server_ts      BIGINT NOT NULL,
    parent_id      TEXT,
    server_seq     BIGINT NOT NULL DEFAULT 0
);

-- Per-project server_seq allocator (audit RACE-1 / M1-1). One row per project,
-- bumped inside the SAME transaction as every events INSERT (see
-- sync-worker/src/events/event-insert.ts): the row lock serializes concurrent
-- same-project writers so two transactions can never compute the same
-- server_seq. Seeded from MAX(events.server_seq) on first use; the bump
-- self-heals if the counter ever falls behind the log (GREATEST against MAX).
-- Gaps in server_seq are possible (idempotent replays still bump) and harmless
-- — server_seq is an ordering key, not a count.
--
-- rebuilt_seq (0036, audit B5): the seq a projection rebuild allocated when
-- it finished. Rebuilds change cells without minting events, so
-- MAX(events.server_seq) — the GET /cells delta/ETag watermark — does not
-- move; any `?since=` cursor below rebuilt_seq is told to resync and the
-- value is folded into the ETag. 0 = never rebuilt.
CREATE TABLE IF NOT EXISTS project_seq_counters (
    project_id  TEXT PRIMARY KEY,
    last_seq    BIGINT NOT NULL,
    rebuilt_seq BIGINT NOT NULL DEFAULT 0
);

-- AD-2 first-child arbitration (audit RACE-2 / M1-1). One row per chain slot
-- (project, file, cell, parent); the first transaction to commit a claim owns
-- the slot, atomically — replacing the check-then-act isWinningChild SELECT
-- for in-flight races. parent_key = parent_id, with '<null>' standing in for
-- genesis events (matches rebuild.ts's in-memory childKey sentinel). The
-- losing sibling's event still lands in `events` (history) but its cells
-- projection write is gated on holding the claim.
CREATE TABLE IF NOT EXISTS chain_claims (
    project_id TEXT NOT NULL,
    file_id    TEXT NOT NULL,
    cell_id    TEXT NOT NULL,
    parent_key TEXT NOT NULL,
    event_id   TEXT NOT NULL,
    PRIMARY KEY (project_id, file_id, cell_id, parent_key)
);

CREATE TABLE files (
    id             TEXT PRIMARY KEY,
    project_id     TEXT NOT NULL,
    name           TEXT NOT NULL,
    role           TEXT,
    kind           TEXT,
    book_code      TEXT,
    source_file_id TEXT,
    anchor_file_id TEXT,
    event_id       TEXT NOT NULL,
    cell_count     INTEGER NOT NULL DEFAULT 0,
    approved_count INTEGER NOT NULL DEFAULT 0,
    word_count     INTEGER NOT NULL DEFAULT 0,
    last_edit_at   BIGINT,
    created_by     TEXT,
    created_at     BIGINT,
    updated_at     BIGINT,
    meta           TEXT NOT NULL DEFAULT '{}',
    filled_count   INTEGER NOT NULL DEFAULT 0,
    -- FRO-272: soft-delete tombstone. NULL = active; epoch-ms = tombstoned.
    -- Cells + audio retained; R2 wipe deferred (see migration 0036).
    deleted_at     BIGINT DEFAULT NULL,
    -- FRO-292: target cells currently marked ai_drafted=1 (machine-drafted, not yet
    -- human-edited or validated). Recomputed by fileCountersRecomputeStmt on every
    -- target.cell.commit or cell.validate projection. Forward-only: 0 for all cells
    -- predating migration 0037.
    ai_drafted_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE cells (
    project_id        TEXT NOT NULL,
    file_id           TEXT NOT NULL,
    cell_id           TEXT NOT NULL,
    side              TEXT NOT NULL CHECK (side IN ('source', 'target')),
    value             TEXT NOT NULL,
    value_html        TEXT,
    type              TEXT,
    canonical_ref     TEXT,
    anchor_cell_id    TEXT,
    event_id          TEXT NOT NULL,
    source_event_id   TEXT,
    last_editor       TEXT,
    last_edit_at      BIGINT NOT NULL,
    validated         INTEGER NOT NULL DEFAULT 0,
    word_count        INTEGER NOT NULL DEFAULT 0,
    content_hash      TEXT,
    endorsement_count INTEGER NOT NULL DEFAULT 0,
    -- FRO-292: 1 when this target cell was machine-drafted (ai_suggestion=true on the
    -- committing event) and has not yet been human-edited or validated. Cleared to 0
    -- by any subsequent human target.cell.commit or cell.validate. Forward-only:
    -- historical commits without the ai_suggestion field default to 0.
    ai_drafted        INTEGER NOT NULL DEFAULT 0,
    start_ms          BIGINT,
    end_ms            BIGINT,
    medium            TEXT,
    sequence_index    DOUBLE PRECISION,
    transcription     TEXT,
    camera_state      TEXT,
    -- OBS parity (0045): extensible per-cell metadata bucket. Mirrors the
    -- extensible source.cell.create payload.metadata. Holds e.g.
    -- { "attachments": [{ "type": "image", "url": "…", "alt": "…" }] };
    -- future keys (gif/video/audio attachments, etc.) need no schema change.
    metadata          JSONB,
    source_location   TEXT,
    -- Replaces SQLite FTS5. Maintained automatically; no triggers needed.
    value_tsv         tsvector GENERATED ALWAYS AS (to_tsvector('simple', value)) STORED,
    PRIMARY KEY (project_id, file_id, cell_id, side)
);

CREATE TABLE cell_validators (
    project_id TEXT NOT NULL,
    file_id    TEXT NOT NULL,
    cell_id    TEXT NOT NULL,
    event_id   TEXT NOT NULL,
    username   TEXT NOT NULL,
    decided_ts BIGINT NOT NULL,
    PRIMARY KEY (project_id, file_id, cell_id, username)
);

CREATE TABLE cell_waivers (
    project_id TEXT NOT NULL,
    file_id    TEXT NOT NULL,
    cell_id    TEXT NOT NULL,
    rule_id    TEXT NOT NULL,
    reason     TEXT,
    waived_by  TEXT NOT NULL,
    waived_ts  BIGINT NOT NULL,
    PRIMARY KEY (project_id, file_id, cell_id, rule_id)
);

CREATE TABLE cell_audio (
    project_id         TEXT NOT NULL,
    file_id            TEXT NOT NULL,
    cell_id            TEXT NOT NULL,
    audio_id           TEXT NOT NULL,
    slot               TEXT NOT NULL,
    url                TEXT NOT NULL,
    mime_type          TEXT,
    voice_id           TEXT,
    reference_audio_id TEXT,
    duration_ms        BIGINT,
    timings_json       TEXT,
    selected           INTEGER NOT NULL DEFAULT 0,
    deleted            INTEGER NOT NULL DEFAULT 0,
    event_id           TEXT NOT NULL,
    created_ts         BIGINT NOT NULL,
    trim_start_ms      BIGINT,
    trim_end_ms        BIGINT,
    PRIMARY KEY (project_id, file_id, cell_id, audio_id)
);

CREATE TABLE cell_backtranslations (
    project_id      TEXT NOT NULL,
    file_id         TEXT NOT NULL,
    cell_id         TEXT NOT NULL,
    target_event_id TEXT NOT NULL,
    bt_text         TEXT NOT NULL,
    bt_html         TEXT,
    polished        INTEGER NOT NULL DEFAULT 0,
    author          TEXT NOT NULL,
    event_id        TEXT NOT NULL,
    server_seq      BIGINT,
    created_at      BIGINT NOT NULL,
    PRIMARY KEY (project_id, file_id, cell_id, target_event_id)
);

CREATE TABLE comments (
    comment_id        TEXT PRIMARY KEY,
    project_id        TEXT NOT NULL,
    scope_kind        TEXT NOT NULL,
    file_id           TEXT,
    cell_id           TEXT,
    parent_comment_id TEXT,
    body              TEXT NOT NULL,
    resolved          INTEGER NOT NULL DEFAULT 0,
    author_id         TEXT NOT NULL,
    author_label      TEXT,
    created_at        BIGINT NOT NULL,
    updated_at        BIGINT NOT NULL,
    deleted_at        BIGINT
);

-- ─────────────────────────── assignments + misc ─────────────────────────

CREATE TABLE assignments (
    assignment_id    TEXT PRIMARY KEY,
    project_id       TEXT NOT NULL,
    assignee_user_id BIGINT NOT NULL,
    scope_kind       TEXT NOT NULL,
    scope_label      TEXT NOT NULL,
    cells_total      INTEGER NOT NULL DEFAULT 0,
    deadline         TEXT,
    note             TEXT,
    created_by       BIGINT NOT NULL,
    created_at       BIGINT NOT NULL,
    unassigned_at    BIGINT,
    completed_at     BIGINT
);

CREATE TABLE assignment_cells (
    assignment_id TEXT NOT NULL,
    file_id       TEXT NOT NULL,
    cell_id       TEXT NOT NULL,
    PRIMARY KEY (assignment_id, file_id, cell_id)
);

CREATE TABLE diarization_jobs (
    id           TEXT PRIMARY KEY,
    project_id   TEXT NOT NULL,
    file_id      TEXT NOT NULL,
    audio_object TEXT NOT NULL,
    fetch_token  TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'queued',
    num_speakers INTEGER,
    turns_json   TEXT,
    error        TEXT,
    created_at   BIGINT NOT NULL,
    updated_at   BIGINT NOT NULL
);

CREATE TABLE file_source_blobs (
    file_id    TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    format     TEXT NOT NULL,
    raw_source TEXT,
    r2_key     TEXT,
    size_bytes BIGINT,
    created_at BIGINT NOT NULL
);

CREATE TABLE checkpoints (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    file_id    TEXT NOT NULL,
    label      TEXT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    r2_key     TEXT NOT NULL
);

-- Migration 0032: per-word morphology for Macula Hebrew + Greek (FRO-178)
CREATE TABLE cell_word_morph (
    project_id  TEXT NOT NULL,
    file_id     TEXT NOT NULL,
    cell_id     TEXT NOT NULL,
    word_seq    INTEGER NOT NULL,   -- 1-based position within the cell
    surface     TEXT NOT NULL,      -- surface form as it appears in the text
    lemma       TEXT,               -- dictionary lemma
    morph_code  TEXT,               -- morphology code (e.g. Macula/OSHB/Robinson format)
    strongs_h   TEXT,               -- Strong's Hebrew number (e.g. H1234), NULL for Greek
    strongs_g   TEXT,               -- Strong's Greek number (e.g. G1234), NULL for Hebrew
    PRIMARY KEY (project_id, file_id, cell_id, word_seq)
);

-- ────────────────────────────── indexes ─────────────────────────────────

CREATE INDEX idx_activity_logs_timestamp ON activity_logs(timestamp);
CREATE INDEX idx_activity_logs_user_id ON activity_logs(user_id);
CREATE INDEX assignment_cells_by_assignment ON assignment_cells(assignment_id);
CREATE INDEX assignments_assignee ON assignments(assignee_user_id);
CREATE INDEX assignments_project ON assignments(project_id);
CREATE INDEX idx_cell_audio_file ON cell_audio(project_id, file_id) WHERE deleted = 0;
CREATE INDEX idx_cell_word_morph_file ON cell_word_morph(project_id, file_id);
CREATE INDEX idx_cell_word_morph_lemma ON cell_word_morph(lemma) WHERE lemma IS NOT NULL;
CREATE INDEX idx_cell_bt_cell ON cell_backtranslations(project_id, file_id, cell_id, created_at DESC);
CREATE INDEX idx_cell_bt_file ON cell_backtranslations(project_id, file_id);
CREATE INDEX idx_cell_validators_cell ON cell_validators(project_id, file_id, cell_id);
CREATE INDEX idx_cell_waivers_file ON cell_waivers(project_id, file_id);
CREATE INDEX idx_cells_decay_drags ON cells(project_id, endorsement_count);
CREATE INDEX idx_cells_file_order ON cells(project_id, file_id, side, anchor_cell_id);
CREATE INDEX idx_cells_last_edit ON cells(project_id, file_id, side, last_edit_at);
CREATE INDEX idx_cells_pair_lookup ON cells(project_id, cell_id, side);
CREATE INDEX idx_cells_source_basis ON cells(source_event_id);
CREATE INDEX idx_cells_validated ON cells(project_id, file_id, side, validated);
-- FTS replacement: GIN over the generated tsvector.
CREATE INDEX idx_cells_value_tsv ON cells USING GIN (value_tsv);
CREATE INDEX idx_checkpoints_file ON checkpoints(file_id, created_at);
CREATE INDEX idx_checkpoints_project ON checkpoints(project_id, created_at);
CREATE INDEX comments_project_scope ON comments(project_id, scope_kind, file_id, cell_id);
CREATE INDEX comments_thread ON comments(project_id, parent_comment_id);
CREATE INDEX idx_diarization_jobs_file ON diarization_jobs(project_id, file_id);
CREATE INDEX idx_events_author ON events(author, server_ts);
CREATE INDEX idx_events_cell ON events(project_id, file_id, cell_id, server_ts);
CREATE INDEX idx_events_file_seq ON events(project_id, file_id, server_seq);
CREATE INDEX idx_events_parent_lookup ON events(project_id, file_id, cell_id, parent_id);
CREATE INDEX idx_events_project ON events(project_id, server_ts);
CREATE UNIQUE INDEX idx_events_project_seq ON events(project_id, server_seq);
CREATE INDEX idx_file_source_blobs_project ON file_source_blobs(project_id);
CREATE INDEX idx_files_anchor_file ON files(anchor_file_id) WHERE anchor_file_id IS NOT NULL;
CREATE INDEX idx_files_last_edit ON files(project_id, last_edit_at);
CREATE INDEX idx_files_project ON files(project_id);
CREATE INDEX idx_files_project_role ON files(project_id, role) WHERE role IS NOT NULL;
CREATE INDEX idx_files_source_file ON files(source_file_id) WHERE source_file_id IS NOT NULL;
CREATE INDEX idx_files_project_active ON files(project_id, deleted_at NULLS FIRST);
CREATE INDEX idx_group_members_user ON group_members(user_id);
CREATE INDEX idx_gpg_project ON group_project_grants(project_id);
CREATE UNIQUE INDEX idx_groups_legacy_uuid ON groups(legacy_uuid);
CREATE INDEX idx_groups_org ON groups(org_id);
CREATE INDEX idx_org_members_org ON org_members(org_id);
CREATE INDEX idx_org_members_user ON org_members(user_id);
CREATE UNIQUE INDEX idx_organizations_legacy_uuid ON organizations(legacy_uuid);
CREATE INDEX idx_organizations_owner ON organizations(owner_user_id);
CREATE INDEX idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX idx_project_invites_project ON project_invites(project_id);
CREATE INDEX idx_project_invites_token ON project_invites(token);
CREATE INDEX idx_project_invites_unused ON project_invites(project_id, used_by) WHERE used_by IS NULL;
CREATE INDEX idx_project_members_user ON project_members(user_id);
CREATE INDEX idx_project_settings_updated_at ON project_settings(updated_at);
CREATE INDEX idx_projects_archived ON projects(archived_at) WHERE archived_at IS NOT NULL;
CREATE INDEX idx_projects_created_by ON projects(created_by);
CREATE INDEX idx_projects_org ON projects(org_id);
CREATE INDEX idx_projects_source_project ON projects(source_project_id) WHERE source_project_id IS NOT NULL;
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);

-- FRO-265: AI budget counters (0034_ai_usage_daily.sql)
CREATE TABLE IF NOT EXISTS ai_usage_daily (
  user_id       INTEGER     NOT NULL,
  date_utc      DATE        NOT NULL,
  request_count INTEGER     NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, date_utc)
);
CREATE INDEX IF NOT EXISTS idx_ai_usage_daily_date ON ai_usage_daily(date_utc);

-- OmniVoice TTS usage metering (0041_tts_usage_daily.sql).
-- Per-user, org-attributed audio-seconds. (user_id=0, org_id=0) = global sentinel.
-- Org totals derived at read time: SUM WHERE org_id = ?
CREATE TABLE IF NOT EXISTS tts_usage_daily (
  user_id       INTEGER          NOT NULL,
  org_id        INTEGER          NOT NULL,
  date_utc      DATE             NOT NULL,
  request_count INTEGER          NOT NULL DEFAULT 0,
  audio_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, org_id, date_utc)
);
CREATE INDEX IF NOT EXISTS idx_tts_usage_org_date ON tts_usage_daily (org_id, date_utc);

-- Org credits & unified compute-cost model (0042_org_credit_usage_daily.sql).
-- Cross-rail cost rollup; rail = 'llm' | 'agent' | 'tts'. raw_cost_cents = actual
-- infra cost; credits derived on read. Existing usage tables unchanged.
CREATE TABLE IF NOT EXISTS org_credit_usage_daily (
  org_id         INTEGER          NOT NULL,
  user_id        INTEGER          NOT NULL,
  date_utc       DATE             NOT NULL,
  rail           TEXT             NOT NULL,
  raw_cost_cents DOUBLE PRECISION NOT NULL DEFAULT 0,
  units          INTEGER          NOT NULL DEFAULT 0,
  PRIMARY KEY (org_id, user_id, date_utc, rail)
);
CREATE INDEX IF NOT EXISTS idx_org_credit_org_date ON org_credit_usage_daily (org_id, date_utc);

-- Translation agent run ledger (0040_agent_runs.sql). One row per
-- POST /api/v1/ai/agent/run; staged commits carry payload.agent_run_id →
-- run_id for attribution / undo-run / cost rollups.
CREATE TABLE IF NOT EXISTS agent_runs (
    run_id      TEXT PRIMARY KEY,
    project_id  TEXT NOT NULL,
    user_id     BIGINT NOT NULL,
    username    TEXT NOT NULL,
    prompt      TEXT NOT NULL,
    model       TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'running', -- running|ok|capped|error
    prompt_tokens     BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    cost_cents  DOUBLE PRECISION NOT NULL DEFAULT 0,
    steps       INTEGER NOT NULL DEFAULT 0,
    started_at  BIGINT NOT NULL,
    ended_at    BIGINT
);
CREATE INDEX IF NOT EXISTS idx_agent_runs_project ON agent_runs (project_id, started_at DESC);

-- ───────────────────────── post-migration notes ─────────────────────────
-- After the bulk data load (Stage C), reset each identity sequence so new
-- inserts don't collide with migrated ids:
--   SELECT setval(pg_get_serial_sequence('users','id'),         COALESCE((SELECT MAX(id) FROM users),1));
--   SELECT setval(pg_get_serial_sequence('organizations','id'), COALESCE((SELECT MAX(id) FROM organizations),1));
--   SELECT setval(pg_get_serial_sequence('groups','id'),        COALESCE((SELECT MAX(id) FROM groups),1));
--   SELECT setval(pg_get_serial_sequence('activity_logs','id'), COALESCE((SELECT MAX(id) FROM activity_logs),1));
--   SELECT setval(pg_get_serial_sequence('password_reset_tokens','id'), COALESCE((SELECT MAX(id) FROM password_reset_tokens),1));
