/**
 * my catalog — GENERATED by `scripts/i18n-catalog.ts import` (AQU-832).
 *
 * Produced by translating the en catalog in an Aquilla project and exporting it
 * back. Do not hand-edit: re-run the import to regenerate. Keys absent here fall
 * back to English per key, so a partial catalog is safe to ship.
 */

import type { Catalog } from "./en"

export const my: Catalog = {}
