import { describe, expect, it } from "vitest"
import { CATALOGS } from "./index"
import { en, type Catalog, type MessageKey } from "./en"
import { DEFAULT_LOCALE, LOCALES } from "../locales"
import { isPluralMessage, PLURAL_CATEGORIES, type MessageValue } from "../plurals"

/**
 * Placeholder integrity of the SHIPPED translated catalogs (AQU-832 follow-up).
 *
 * `context.test.ts` already checks that every placeholder in the *English* base
 * is documented for translators. Nothing checked the other end of the loop: that
 * what comes BACK from translation still carries the same placeholders.
 *
 * That gap matters because `interpolate()` (translate.ts) substitutes by name and
 * **leaves an unknown `{placeholder}` in the output verbatim**. So a translation
 * that renames `{count}` to `{cuenta}`, or invents `{total}`, does not throw and
 * does not fall back — it renders literal braces to the user, in that locale
 * only, on whatever screen the key lives. Nothing in the type system can catch
 * it: catalog values are plain strings.
 *
 * The catalogs are generated by `scripts/i18n-catalog.ts import` from work done
 * outside this repo (a translation project, or a machine-translation pass), so
 * this is the boundary where imported data becomes shipping code. It is exactly
 * the place to validate it.
 *
 * ## Why the rule is "subset", not "equal"
 *
 * A locale legitimately varies placeholders BETWEEN plural forms. English writes
 * two forms and often drops the numeral from the singular ("one file" vs
 * "{count} files"); Arabic writes six and may want `{count}` in forms English
 * omits it from — or may drop it where the word already implies the number.
 * Requiring per-form equality would fail those correct translations.
 *
 * What is never legitimate is a placeholder the app will not supply a value for.
 * So the check is: every placeholder a translated form uses must be one the
 * English side of that key offers (in ANY of its forms), plus the plural key's
 * own `countVar`, which `translate()` always supplies.
 *
 * Dropping a placeholder is not failed here — it loses information but renders
 * clean text, and for a plural form it is often the correct choice.
 */

const placeholdersIn = (s: string): Set<string> =>
  new Set([...s.matchAll(/\{(\w+)\}/g)].map((m) => m[1]))

/** Every placeholder the English side of a key can supply, plus its count var. */
function allowedFor(key: MessageKey): Set<string> | null {
  const base = en[key]
  // Stale translated keys (English removed the message) are not a placeholder
  // issue — skip them so this suite fails on braces, not `undefined.matchAll`.
  if (base === undefined) return null
  const allowed = new Set<string>()
  if (isPluralMessage(base)) {
    for (const category of PLURAL_CATEGORIES) {
      const form = base.forms[category]
      if (form !== undefined) for (const p of placeholdersIn(form)) allowed.add(p)
    }
    // `translate()` always passes the governing count through, even when the
    // English form that category maps to happens not to render it.
    allowed.add(base.countVar ?? "count")
  } else {
    for (const p of placeholdersIn(base)) allowed.add(p)
  }
  return allowed
}

/** (category label, string) pairs for a catalog value — one entry if plain. */
function formsOf(value: MessageValue): Array<[string, string]> {
  if (!isPluralMessage(value)) return [["", value]]
  return PLURAL_CATEGORIES.flatMap((c) => {
    const form = value.forms[c]
    return form === undefined ? [] : [[c, form] as [string, string]]
  })
}

const translatedLocales = LOCALES.filter((l) => l.code !== DEFAULT_LOCALE)

describe("translated catalogs preserve placeholder integrity", () => {
  it.each(translatedLocales.map((l) => [l.code] as const))(
    "%s introduces no placeholder the app cannot fill",
    (code) => {
      const catalog = CATALOGS[code] as Catalog | undefined
      expect(catalog, `no catalog registered for "${code}"`).toBeDefined()

      const offenders: string[] = []
      for (const [key, value] of Object.entries(catalog ?? {})) {
        if (value === undefined) continue
        const allowed = allowedFor(key as MessageKey)
        if (allowed === null) continue
        for (const [category, form] of formsOf(value)) {
          for (const name of placeholdersIn(form)) {
            if (allowed.has(name)) continue
            const where = category ? `${key}#${category}` : key
            offenders.push(
              `${where}: uses {${name}}, but English offers only ` +
                `{${[...allowed].join("} {")}} — it would render as literal braces`,
            )
          }
        }
      }
      expect(offenders, offenders.join("\n")).toEqual([])
    },
  )

  it.each(translatedLocales.map((l) => [l.code] as const))(
    "%s keeps every placeholder of a non-counted message",
    (code) => {
      // For a plain string there is no plural-form variation to excuse a drop:
      // the English author put the placeholder there because the sentence needs
      // the value, so losing it loses information the user was meant to see.
      const catalog = CATALOGS[code] as Catalog | undefined
      const offenders: string[] = []
      for (const [key, value] of Object.entries(catalog ?? {})) {
        if (value === undefined) continue
        const base = en[key as MessageKey]
        if (base === undefined) continue
        if (isPluralMessage(base) || isPluralMessage(value)) continue
        const expected = placeholdersIn(base)
        const actual = placeholdersIn(value)
        const missing = [...expected].filter((p) => !actual.has(p))
        if (missing.length > 0) {
          offenders.push(`${key}: drops {${missing.join("} {")}}`)
        }
      }
      expect(offenders, offenders.join("\n")).toEqual([])
    },
  )
})
