// Inworld Realtime TTS-2 / TTS-2 Flash language subtags.
// https://docs.inworld.ai/tts/capabilities/multilingual
//
// Inworld's "200+" figure counts languages *and* regional locales (en-US,
// es-MX, …). The published table is the Language dropdown (~95 subtags).
// Regional tags are accents: INWORLD_LANGUAGE_CODES plus SYSTEM catalog.

/** Tier 1 — most extensively evaluated. */
const TIER_1 = [
  "ar",
  "zh",
  "nl",
  "en",
  "fr",
  "de",
  "he",
  "hi",
  "it",
  "ja",
  "ko",
  "pl",
  "pt",
  "ru",
  "es",
] as const

/** Tier 2 — fully supported; ISO 639-1, or ISO 639-3 when there is no 2-letter tag. */
const TIER_2 = [
  "af",
  "sq",
  "am",
  "hy",
  "as",
  "az",
  "eu",
  "be",
  "bn",
  "bg",
  "my",
  "yue",
  "ca",
  "ceb",
  "hr",
  "cs",
  "da",
  "yih",
  "arz",
  "et",
  "fil",
  "fi",
  "gl",
  "gbm",
  "ka",
  "el",
  "gu",
  "afb",
  "ht",
  "acw",
  "hu",
  "is",
  "id",
  "jv",
  "kn",
  "kk",
  "kok",
  "lo",
  "lv",
  "ayl",
  "lt",
  "lb",
  "mk",
  "mai",
  "mg",
  "ms",
  "ml",
  "mr",
  "mn",
  "ars",
  "ne",
  "uzn",
  "nb",
  "nn",
  "or",
  "acx",
  "ps",
  "fa",
  "pms",
  "pa",
  "ro",
  "sr",
  "sd",
  "si",
  "sk",
  "sl",
  "sw",
  "sv",
  "ta",
  "te",
  "th",
  "aeb",
  "tr",
  "uk",
  "ur",
  "uz",
  "vi",
  "vro",
  "cy",
] as const

export const INWORLD_TTS2_LANGUAGE_CODES: readonly string[] = [...TIER_1, ...TIER_2]

/**
 * English names for subtags `Intl.DisplayNames` does not cover (mostly
 * ISO 639-3 dialects on Inworld's Tier 2 table).
 */
export const INWORLD_TTS2_LANGUAGE_NAMES: Readonly<Record<string, string>> = {
  acw: "Hijazi Arabic",
  acx: "Omani Arabic",
  aeb: "Tunisian Arabic",
  afb: "Gulf Arabic",
  ars: "Najdi Arabic",
  arz: "Egyptian Arabic",
  ayl: "Libyan Arabic",
  gbm: "Garhwali",
  pms: "Piedmontese",
  uzn: "Northern Uzbek",
  vro: "Võro",
  yih: "Eastern Yiddish",
}
