-- 0044_email_verification.sql
-- Soft email verification. A token is minted at registration and emailed; the
-- user clicks it to set users.email_verified_at. Non-blocking — registration
-- still returns a session, so an unverified user is never locked out.
ALTER TABLE users ADD COLUMN email_verified_at TIMESTAMPTZ;

CREATE TABLE email_verification_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token      TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_email_verification_tokens_token ON email_verification_tokens(token);
