-- 0047_platform_settings_and_admin_elevation.sql
--
-- Two features for the hardened platform-admin console (see routes/admin.ts,
-- lib/platform-settings.ts, middleware/platform-admin.ts):
--
--   1. platform_settings — a single global row holding runtime-editable AI
--      config (chat model, agent model, allowed-models, AI budgets). Mirrors
--      org_settings: a versioned JSON blob with optimistic-concurrency writes.
--      Read on the chat/agent hot path (cached ~30s) with wrangler.toml env
--      vars as the fallback when a key is unset.
--
--   2. Step-up "sudo" gate for the admin console. admin_elevation_codes holds
--      short-lived 6-digit codes emailed to the operator (clone of
--      password_reset_tokens); admin_elevations holds the resulting elevated
--      session (one row per user, expires after ELEVATION_SESSION_HOURS); and
--      admin_audit_log records elevations + settings changes for accountability.

-- 1. Global settings — only ever one row (id = 1).
CREATE TABLE platform_settings (
    id         INTEGER PRIMARY KEY DEFAULT 1,
    settings   TEXT NOT NULL DEFAULT '{}',
    version    INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by BIGINT REFERENCES users(id),
    CONSTRAINT platform_settings_singleton CHECK (id = 1)
);

-- 2a. Short-lived elevation codes (single-use; verified then deleted).
CREATE TABLE admin_elevation_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    code       TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_admin_elevation_codes_user ON admin_elevation_codes(user_id);

-- 2b. Active elevated sessions — one row per user, refreshed on each verify.
CREATE TABLE admin_elevations (
    user_id        BIGINT PRIMARY KEY,
    elevated_until TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ DEFAULT now()
);

-- 2c. Audit trail for sensitive admin actions (elevation grants, settings edits).
CREATE TABLE admin_audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    action     TEXT NOT NULL,
    detail     TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_admin_audit_log_created ON admin_audit_log(created_at);
