-- Migration 0066: auth & session-management hardening ([Pen test] 2026-07-20
-- weekly review — Monday theme).
--
-- Two independent additions, both idempotent:
--
-- 1. users.password_changed_at — stamped by POST /api/v2/auth/password-reset/reset
--    on a successful reset. authMiddleware rejects any access token whose `iat`
--    predates this timestamp. Access tokens default to a 30-day lifetime
--    (ACCESS_TOKEN_EXPIRE_MINUTES=43200) and there was previously no way to
--    invalidate an already-issued token — so a stolen/leaked JWT survived a
--    password reset for up to 30 more days. NULL means "never reset via this
--    flow" and imposes no floor (existing tokens keep verifying).
--
-- 2. auth_rate_limit_events — backs the login (POST /api/v2/auth/token) and
--    password-reset-request throttles. Previously neither endpoint had any
--    attempt limiting, so both were open to unthrottled credential
--    stuffing / password guessing and password-reset email bombing.
--
-- Apply by hand against Neon (same convention as prior migrations in this
-- directory — NOT applied automatically):
--   set -a; . ./.env; set +a
--   npx tsx scripts/pg.ts db/postgres/migrations/0066_auth_session_hardening.sql
-- Verify: `password_changed_at` appears on `users`; `auth_rate_limit_events`
-- exists with the `idx_auth_rate_limit_lookup` index.

ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS auth_rate_limit_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       TEXT NOT NULL,
    identifier TEXT NOT NULL,
    success    INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auth_rate_limit_lookup
  ON auth_rate_limit_events(kind, identifier, created_at);
