-- 0076: Stripe Field Plan billing + word-metered AI credits.
--
-- Additive only. Existing orgs keep working with no row in org_billing
-- (treated as plan=none: record words, do not enforce a paid allowance).
-- Old SPA builds ignore the new /billing routes. Safe to apply before
-- client distros ship — no existing table is rewritten, no required
-- column is added to a hot path.
--
-- NOT applied automatically to live Neon branches. Apply by hand:
--   set -a; . ./.env; set +a
--   npx tsx scripts/pg.ts db/postgres/migrations/0076_org_billing.sql

CREATE TABLE IF NOT EXISTS org_billing (
  org_id                   BIGINT PRIMARY KEY,
  stripe_customer_id       TEXT UNIQUE,
  stripe_subscription_id   TEXT UNIQUE,
  plan                     TEXT NOT NULL DEFAULT 'none',
  status                   TEXT NOT NULL DEFAULT 'none',
  current_period_start     TIMESTAMPTZ,
  current_period_end       TIMESTAMPTZ,
  addon_packs              INTEGER NOT NULL DEFAULT 0,
  hard_cap_words           BIGINT,
  created_at               TIMESTAMPTZ DEFAULT now(),
  updated_at               TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS org_word_usage_daily (
  org_id     BIGINT  NOT NULL,
  user_id    BIGINT  NOT NULL,
  date_utc   DATE    NOT NULL,
  rail       TEXT    NOT NULL,
  words      INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (org_id, user_id, date_utc, rail)
);
CREATE INDEX IF NOT EXISTS idx_org_word_org_date ON org_word_usage_daily (org_id, date_utc);

CREATE TABLE IF NOT EXISTS org_billing_events (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id          BIGINT,
  stripe_event_id TEXT UNIQUE,
  kind            TEXT NOT NULL,
  payload_json    TEXT,
  created_at      TIMESTAMPTZ DEFAULT now()
);
