-- Migration 0085 (AQU-1180): scrub human identity from agent-facing API
-- responses.
--
-- The Agent API returned translator identity by default — `GET /me` handed
-- back the minting user's username, every cell in a read carried
-- `lastEditor`, and every event in a history carried `author`. A PAT pasted
-- into an AI console therefore shipped the project's roster into that
-- vendor's context and logs. For translation teams in restricted regions
-- that is a safety exposure, not a preference (docs/OPSEC.md).
--
-- Three shapes, all defaulting to the safe side:
--
-- 1. `api_credentials.pii` — opt-IN per token, default false. A token without
--    it sees stable per-project pseudonyms (`u_xxxxxxxx`) instead of names.
--    Only an OWNER of the credential's scope may mint one with it on
--    (auth-worker/src/routes/credentials.ts).
--
-- 2. `project_settings.agent_authorship` — a STORED generated column over the
--    settings blob's `agentAuthorship` key, so the read path never loads the
--    multi-MB blob to answer "does this project allow author fields at all?"
--    (same reason as the 0054/AQU-575 generated columns above it). Value
--    'none' drops author fields entirely — absent, not blanked — for teams
--    where even pseudonymous correlation ("u_7f3a edited 400 cells at 2am
--    Kyiv time") is too much. NULL/anything else = the pseudonymous default.
--
-- 3. `agent_read_audit` — one row per agent read call, so a leak found later
--    can be traced back to the credential that pulled it. Deliberately one
--    row per CALL (with the scope it read and how many rows came back), not
--    one per cell: an agent sweeping a project would otherwise write millions
--    of rows on the read path.

ALTER TABLE api_credentials
  ADD COLUMN IF NOT EXISTS pii BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE project_settings
  ADD COLUMN IF NOT EXISTS agent_authorship TEXT
  GENERATED ALWAYS AS ((settings::jsonb)->>'agentAuthorship') STORED;

CREATE TABLE IF NOT EXISTS agent_read_audit (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id TEXT NOT NULL,
    project_id    TEXT,
    -- Which read surface: 'cells' | 'history' | 'search' | 'files'.
    resource      TEXT NOT NULL,
    -- The scope read: the fileId for cells, the cellId for history, null for
    -- project-wide reads. Together with `resource` this answers "which cells
    -- did this credential see".
    resource_id   TEXT,
    -- How many rows the call returned.
    row_count     INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The trace query: everything one credential read, newest first.
CREATE INDEX IF NOT EXISTS idx_agent_read_audit_credential
  ON agent_read_audit(credential_id, created_at DESC);
-- The blast-radius query: who read this project.
CREATE INDEX IF NOT EXISTS idx_agent_read_audit_project
  ON agent_read_audit(project_id, created_at DESC);
